/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-06 12:03:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class bidHistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    if (session.getAttribute("username") == null) {
        response.sendRedirect("../LoginPage/login.jsp");
        return;
    }

    String username = (String) session.getAttribute("username");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Bid History</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3>User: ");
      out.print( username );
      out.write("</h3>\r\n");
      out.write("<a href=\"notifications.jsp\">Back to Notifications</a>\r\n");
      out.write("<hr/>\r\n");
      out.write("\r\n");

    String itemType   = request.getParameter("itemType");     // tops, bottoms, shoes
    String itemIdParam = request.getParameter("itemIdValue"); // id in that table

    if (itemType == null || itemType.trim().isEmpty()
            || itemIdParam == null || itemIdParam.trim().isEmpty()) {

        out.println("<p style='color:red;'>No item selected.</p>");
    } else {

        itemType = itemType.trim();
        int itemIdValue = Integer.parseInt(itemIdParam);

        String tableName;
        String idColumn;

        if ("tops".equals(itemType)) {
            tableName = "tops";
            idColumn  = "topIdValue";
        } else if ("bottoms".equals(itemType)) {
            tableName = "bottoms";
            idColumn  = "bottomIdValue";
        } else if ("shoes".equals(itemType)) {
            tableName = "shoes";
            idColumn  = "shoeIdValue";
        } else {
            out.println("<p style='color:red;'>Invalid item type.</p>");
            tableName = null;
            idColumn = null;
        }

        if (tableName != null) {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = null;
            PreparedStatement psItem = null;
            PreparedStatement psBids = null;
            ResultSet rsItem = null;
            ResultSet rsBids = null;

            try {
                con = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/thriftShop", "root", "12345");

                String sqlItem =
                        "select i.*, u.usernameValue as sellerUsername " +
                                "from " + tableName + " i " +
                                "join users u on i.auctionSellerIdValue = u.userIdValue " +
                                "where i." + idColumn + " = ?";

                psItem = con.prepareStatement(sqlItem);
                psItem.setInt(1, itemIdValue);
                rsItem = psItem.executeQuery();

                if (rsItem.next()) {
                    String sellerUsername = rsItem.getString("sellerUsername");
                    String genderValueDisplay = rsItem.getString("genderValue");
                    String sizeValueDisplay = rsItem.getString("sizeValue");
                    String colorValueDisplay = rsItem.getString("colorValue");
                    String descriptionValueDisplay = rsItem.getString("descriptionValue");
                    String conditionValueDisplay = rsItem.getString("conditionValue");
                    float minimumBidPriceValueDisplay = rsItem.getFloat("minimumBidPriceValue");
                    float startingOrCurrentBidPriceValueDisplay = rsItem.getFloat("startingOrCurrentBidPriceValue");
                    String auctionCloseDateValueDisplay = rsItem.getString("auctionCloseDateValue");
                    String auctionCloseTimeValueDisplay = rsItem.getString("auctionCloseTimeValue");

                    out.println("<h2>Bid History for " + itemType +
                            " item id: " + itemIdValue + "</h2>");
                    out.println("<p><strong>Seller:</strong> " + sellerUsername + "</p>");
                    out.println("<p><strong>Gender:</strong> " + genderValueDisplay + "</p>");
                    out.println("<p><strong>Size:</strong> " + sizeValueDisplay + "</p>");
                    out.println("<p><strong>Color:</strong> " + colorValueDisplay + "</p>");
                    out.println("<p><strong>Description:</strong> " + descriptionValueDisplay + "</p>");
                    out.println("<p><strong>Condition:</strong> " + conditionValueDisplay + "</p>");
                    if (minimumBidPriceValueDisplay != 0.0f) {
                        out.println("<p><strong>Minimum Bid Price:</strong> " + minimumBidPriceValueDisplay + "</p>");
                    } else {
                        out.println("<p><strong>Minimum Bid Price:</strong> None</p>");
                    }
                    out.println("<p><strong>Current Bid Price:</strong> " + startingOrCurrentBidPriceValueDisplay + "</p>");
                    out.println("<p><strong>Auction Close Date:</strong> " + auctionCloseDateValueDisplay + "</p>");
                    out.println("<p><strong>Auction Close Time:</strong> " + auctionCloseTimeValueDisplay + "</p>");
                    out.println("<hr/>");
                } else {
                    out.println("<p style='color:red;'>Item not found.</p>");
                }

                if (rsItem != null) rsItem.close();
                if (psItem != null) psItem.close();

                String sqlBids =
                        "select b.bidIdValue, b.newBidValue, b.bidIncrementValue, b.bidMaxValue, " +
                                "       b.buyerIdValue, u.usernameValue as bidderUsername " +
                                "from incrementbids b " +
                                "join users u on b.buyerIdValue = u.userIdValue " +
                                "where b.itemTypeValue = ? and b.itemIdValue = ? " +
                                "order by b.bidIdValue desc";

                psBids = con.prepareStatement(sqlBids);
                psBids.setString(1, itemType);
                psBids.setInt(2, itemIdValue);
                rsBids = psBids.executeQuery();

                boolean hasBids = false;

                out.println("<h3>Bid History</h3>");
                out.println("<table border='1' cellpadding='5' cellspacing='0'>");
                out.println("<tr>");
                out.println("<th>Bid ID</th>");
                out.println("<th>Bidder</th>");
                out.println("<th>Bid Amount</th>");
                out.println("<th>Increment</th>");
                out.println("<th>Max Auto Bid</th>");
                out.println("</tr>");

                while (rsBids.next()) {
                    hasBids = true;
                    int bidId = rsBids.getInt("bidIdValue");
                    String bidderUsername = rsBids.getString("bidderUsername");
                    float newBidValue = rsBids.getFloat("newBidValue");
                    String bidIncrementValue = rsBids.getString("bidIncrementValue");
                    String bidMaxValue = rsBids.getString("bidMaxValue");

                    out.println("<tr>");
                    out.println("<td>" + bidId + "</td>");
                    out.println("<td>" + bidderUsername + "</td>");
                    out.println("<td>" + newBidValue + "</td>");
                    out.println("<td>" + bidIncrementValue + "</td>");
                    out.println("<td>" + bidMaxValue + "</td>");
                    out.println("</tr>");
                }

                out.println("</table>");

                if (!hasBids) {
                    out.println("<p>No bids have been placed yet for this item.</p>");
                }

                if (rsBids != null) rsBids.close();
                if (psBids != null) psBids.close();
                if (con != null) con.close();

            } catch (Exception e) {
                e.printStackTrace();
                out.println("<p style='color:red;'>Error: " + e.getMessage() + "</p>");
            }
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
