/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-07 00:10:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.io.*;
import java.sql.*;

public final class bidPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    // make sure user is logged in
    if (session.getAttribute("userIdValue") == null) {
        response.sendRedirect("../LoginPage/login.jsp");
        return;
    }

    Class.forName("com.mysql.cj.jdbc.Driver");
    String jdbcUrl = System.getenv("JDBC_URL");
    if (jdbcUrl == null || jdbcUrl.isEmpty()) {
        String dbHost = System.getenv("DB_HOST");
        String dbPort = System.getenv("DB_PORT");
        String dbName = System.getenv("DB_NAME");
        if (dbHost == null) dbHost = "localhost";
        if (dbPort == null) dbPort = "3306";
        if (dbName == null) dbName = "thriftShop";
        jdbcUrl = "jdbc:mysql://" + dbHost + ":" + dbPort + "/" + dbName;
    }
    String dbUser = System.getenv("DB_USER");
    if (dbUser == null) dbUser = "root";
    String dbPass = System.getenv("DB_PASS");
    if (dbPass == null) dbPass = "12345";
    Connection con = DriverManager.getConnection(jdbcUrl, dbUser, dbPass);
    Statement st = con.createStatement();

    String topIdParam = request.getParameter("topIdValue");

    if (topIdParam != null && !topIdParam.trim().isEmpty()) {

        Integer topIdValue = Integer.parseInt(topIdParam);
        Float setnewbid = Float.parseFloat(request.getParameter("setNewBid"));
        Integer userIdValue = (Integer) session.getAttribute("userIdValue");
        String setautomaticbidincrementprice = request.getParameter("SetAutomaticBidIncrementPrice");
        String maxbidprice = request.getParameter("maxBidPrice");

        // get current bid from tops
        String returnCurrentBidPrice =
                "select startingOrCurrentBidPriceValue " +
                        "from tops where topIdValue = " + topIdValue;
        ResultSet currentBidPrice = st.executeQuery(returnCurrentBidPrice);

        if (currentBidPrice.next()) {
            Float currentBidPriceValue =
                    currentBidPrice.getFloat("startingOrCurrentBidPriceValue");

            if (setnewbid > currentBidPriceValue) {

                // insert into incrementbids, not topsincrementbids
                // and use itemTypeValue + itemIdValue
                String insertSql =
                        "insert into incrementbids " +
                                " (buyerIdValue, newBidValue, bidIncrementValue, bidMaxValue, " +
                                "  itemTypeValue, itemIdValue) " +
                                " values (?, ?, ?, ?, ?, ?)";

                PreparedStatement psInsert = con.prepareStatement(insertSql);
                psInsert.setInt(1, userIdValue);
                psInsert.setFloat(2, setnewbid);
                psInsert.setString(3, setautomaticbidincrementprice);
                psInsert.setString(4, maxbidprice);
                psInsert.setString(5, "tops");
                psInsert.setInt(6, topIdValue);
                psInsert.executeUpdate();
                psInsert.close();

                // update current price on tops
                String updateSql =
                        "update tops set startingOrCurrentBidPriceValue = ? " +
                                "where topIdValue = ?";
                PreparedStatement psUpdate = con.prepareStatement(updateSql);
                psUpdate.setFloat(1, setnewbid);
                psUpdate.setInt(2, topIdValue);
                psUpdate.executeUpdate();
                psUpdate.close();

                session.setAttribute("alertMessage", "success");
            } else {
                session.setAttribute("alertMessage", "fail");
            }
        }
        currentBidPrice.close();
    }

    st.close();
    con.close();

    response.sendRedirect("tops.jsp");

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
