/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-06 10:06:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.Part;
import java.io.*;
import java.sql.*;
import jakarta.servlet.annotation.MultipartConfig;

public final class bidPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("jakarta.servlet.http.Part");
    _jspx_imports_classes.add("jakarta.servlet.annotation.MultipartConfig");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Connection con = null;
    PreparedStatement psSelect = null;
    PreparedStatement psInsert = null;
    PreparedStatement psUpdate = null;
    ResultSet currentBidPrice = null;

    String redirectPage = "tops.jsp";

    try {
        // connect to the same DB as your other pages
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/thriftShop", "root", "12345");

        // read id that comes from the form
        String topIdParam = request.getParameter("topIdValue");

        if (topIdParam != null && !topIdParam.isEmpty()) {

            int topIdValue = Integer.parseInt(topIdParam);

            if (topIdValue > 0) {
                // form fields
                String setNewBidStr = request.getParameter("setNewBid");
                String incrStr      = request.getParameter("SetAutomaticBidIncrementPrice");
                String maxBidStr    = request.getParameter("maxBidPrice");

                // user info from session
                Integer userIdValue = (Integer) session.getAttribute("userIdValue");
                String username     = (String) session.getAttribute("username");

                if (setNewBidStr != null && !setNewBidStr.isEmpty()
                        && userIdValue != null) {

                    float setNewBid = Float.parseFloat(setNewBidStr);

                    // default values if auto bid fields are empty
                    float incrValue   = 0.0f;
                    float maxBidValue = 0.0f;

                    if (incrStr != null && !incrStr.isEmpty()) {
                        incrValue = Float.parseFloat(incrStr);
                    }
                    if (maxBidStr != null && !maxBidStr.isEmpty()) {
                        maxBidValue = Float.parseFloat(maxBidStr);
                    }

                    // 1. get current price from tops
                    String sqlSelect =
                            "select startingOrCurrentBidPriceValue " +
                                    "from tops where topIdValue = ?";
                    psSelect = con.prepareStatement(sqlSelect);
                    psSelect.setInt(1, topIdValue);
                    currentBidPrice = psSelect.executeQuery();

                    if (currentBidPrice.next()) {
                        float currentBidPriceValue =
                                currentBidPrice.getFloat("startingOrCurrentBidPriceValue");

                        if (setNewBid > currentBidPriceValue) {

                            // 2. insert into topsIncrementBids
                            String sqlInsert =
                                    "insert into topsIncrementBids " +
                                            "(topIdValue, buyerIdValue, newBidValue, bidIncrementValue, bidMaxValue) " +
                                            "values (?, ?, ?, ?, ?)";
                            psInsert = con.prepareStatement(sqlInsert);
                            psInsert.setInt(1, topIdValue);
                            psInsert.setInt(2, userIdValue);
                            psInsert.setFloat(3, setNewBid);
                            psInsert.setFloat(4, incrValue);
                            psInsert.setFloat(5, maxBidValue);

                            int insertedRows = psInsert.executeUpdate();

                            // 3. update tops table current price
                            String sqlUpdate =
                                    "update tops set startingOrCurrentBidPriceValue = ? " +
                                            "where topIdValue = ?";
                            psUpdate = con.prepareStatement(sqlUpdate);
                            psUpdate.setFloat(1, setNewBid);
                            psUpdate.setInt(2, topIdValue);

                            int updatedRows = psUpdate.executeUpdate();

                            if (insertedRows > 0 && updatedRows > 0) {
                                session.setAttribute("alertMessage", "success");

                                // store bid amount by user info too
                                session.setAttribute("lastBidAmount", setNewBid);
                                session.setAttribute("lastBidUserId", userIdValue);
                                if (username != null) {
                                    session.setAttribute("lastBidUsername", username);
                                }
                                session.setAttribute("lastBidTopId", topIdValue);
                            } else {
                                session.setAttribute("alertMessage", "fail");
                            }
                        } else {
                            // new bid is not higher
                            session.setAttribute("alertMessage", "fail");
                        }
                    } else {
                        // no such topIdValue
                        session.setAttribute("alertMessage", "fail");
                    }
                } else {
                    // missing bid or user id
                    session.setAttribute("alertMessage", "fail");
                }
            }
        }

    } catch (Exception e) {
        e.printStackTrace(); // check Tomcat console if needed
        session.setAttribute("alertMessage", "fail");
    } finally {
        try { if (currentBidPrice != null) currentBidPrice.close(); } catch (Exception ignore) {}
        try { if (psSelect != null) psSelect.close(); } catch (Exception ignore) {}
        try { if (psInsert != null) psInsert.close(); } catch (Exception ignore) {}
        try { if (psUpdate != null) psUpdate.close(); } catch (Exception ignore) {}
        try { if (con != null) con.close(); } catch (Exception ignore) {}
    }

    // back to tops page
    response.sendRedirect(redirectPage);

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
