/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-06 08:04:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.Part;
import java.io.*;
import java.sql.*;
import jakarta.servlet.annotation.MultipartConfig;

public final class bottoms_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("jakarta.servlet.http.Part");
    _jspx_imports_classes.add("jakarta.servlet.annotation.MultipartConfig");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/thriftShop","root", "12345");
    Statement st = con.createStatement();

    if (session.getAttribute("username") == null) {
        response.sendRedirect("../LoginPage/login.jsp");
        return;
    }
    out.println("<h3>User: " + session.getAttribute("username") + "</h3>");

    out.println("<a href='../WebsitePages/mainPage.jsp'>Main Page</a>");
    out.println("<br/>This is the Bottoms page<br/><br/>");

    String gender = request.getParameter("bottomGender");
    if (gender != null) {
        Integer userIdValue = (Integer) session.getAttribute("userIdValue");
        String size = request.getParameter("bottomSize");
        String color = request.getParameter("bottomColor");
        Float waistlength  = Float.parseFloat(request.getParameter("WaistLength"));
        Float inseamlength = Float.parseFloat(request.getParameter("InseamLength"));
        Float outseamlength= Float.parseFloat(request.getParameter("OutseamLength"));
        Float hiplength    = Float.parseFloat(request.getParameter("HipLength"));
        Float riselength   = Float.parseFloat(request.getParameter("RiseLength"));
        String description = request.getParameter("Description");
        String condition   = request.getParameter("Condition");
        String minimum     = request.getParameter("Minimum");
        String auctionclosedate = request.getParameter("AuctionCloseDateBottoms");
        String auctionclosetime = request.getParameter("AuctionCloseTimeBottoms");

        if (minimum == null || minimum.isEmpty()) {
            minimum = "0.0";
        }

        String insertBottomInformation =
                "insert into bottoms " +
                        "(auctionSellerIdValue, genderValue, sizeValue, colorValue, " +
                        " waistLengthValue, inseamLengthValue, outseamLengthValue, " +
                        " hipLengthValue, riseLengthValue, descriptionValue, conditionValue, " +
                        " minimumBidPriceValue, auctionCloseDateValue, auctionCloseTimeValue) " +
                        "values ('" + userIdValue + "','" + gender + "','" + size + "','" + color + "'," +
                        "'" + waistlength + "','" + inseamlength + "','" + outseamlength + "'," +
                        "'" + hiplength + "','" + riselength + "','" + description + "','" + condition + "'," +
                        "'" + minimum + "','" + auctionclosedate + "','" + auctionclosetime + "')";

        int insertedRows = st.executeUpdate(insertBottomInformation);
    }

    ResultSet rs = st.executeQuery("select * from bottoms order by bottomIdValue desc");
    while (rs.next()) {
        String genderValueDisplay       = rs.getString("genderValue");
        String sizeValueDisplay         = rs.getString("sizeValue");
        String colorValueDisplay        = rs.getString("colorValue");
        String waistLengthValueDisplay  = rs.getString("waistLengthValue");
        String inseamLengthValueDisplay = rs.getString("inseamLengthValue");
        String outseamLengthValueDisplay= rs.getString("outseamLengthValue");
        String hipLengthValueDisplay    = rs.getString("hipLengthValue");
        String riseLengthValueDisplay   = rs.getString("riseLengthValue");
        String descriptionValueDisplay  = rs.getString("descriptionValue");
        String conditionValueDisplay    = rs.getString("conditionValue");
        float minimumBidPriceValueDisplay = rs.getFloat("minimumBidPriceValue");
        String auctionCloseDateValueDisplay = rs.getString("auctionCloseDateValue");
        String auctionCloseTimeValueDisplay = rs.getString("auctionCloseTimeValue");

        out.println("<div style='margin-bottom: 100px;'>");
        out.println("<p>Gender: " + genderValueDisplay + "</p>");
        out.println("<p>Size: " + sizeValueDisplay + "</p>");
        out.println("<p>Color: " + colorValueDisplay + "</p>");

        out.println("<p>Waist Length: " + waistLengthValueDisplay + "</p>");
        out.println("<p>Inseam Length: " + inseamLengthValueDisplay + "</p>");
        out.println("<p>Outseam Length: " + outseamLengthValueDisplay + "</p>");
        out.println("<p>Hip Length: " + hipLengthValueDisplay + "</p>");
        out.println("<p>Rise Length: " + riseLengthValueDisplay + "</p>");

        out.println("<p>Description: " + descriptionValueDisplay + "</p>");
        out.println("<p>Condition: " + conditionValueDisplay + "</p>");

        if (minimumBidPriceValueDisplay != 0.0f) {
            out.println("<p>Minimum Bid Price: " + minimumBidPriceValueDisplay + "</p>");
        } else {
            out.println("<p>Minimum Bid Price: None</p>");
        }

        out.println("<p>Auction Close Date: " + auctionCloseDateValueDisplay + "</p>");
        out.println("<p>Auction Close Time: " + auctionCloseTimeValueDisplay + "</p>");
        out.println("</div>");
    }



    rs.close();
    st.close();
    con.close();

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
