/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-07 00:39:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.time.LocalDate;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    ");

        if (session.getAttribute("username") == null) {
            response.sendRedirect("../LoginPage/login.jsp");
            return;

        }
        LocalDate today = LocalDate.now();
    
      out.write("\n");
      out.write("        <!DOCTYPE html>\n");
      out.write("        <html>\n");
      out.write("        <head>\n");
      out.write("            <meta charset=\"UTF-8\">\n");
      out.write("            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("            <title>ThriftShop Auction - Main Page</title>\n");
      out.write("            <link rel=\"stylesheet\" href=\"../css/auction-style.css\">\n");
      out.write("            <script>\n");
      out.write("                // Make functions available globally - defined in head so they're available immediately\n");
      out.write("                function createAuction() {\n");
      out.write("                    // Try to find existing modal first\n");
      out.write("                    var modal = document.getElementById('createAuctionModal');\n");
      out.write("                    \n");
      out.write("                    if (modal) {\n");
      out.write("                        // Modal exists, just show it\n");
      out.write("                        modal.style.display = 'block';\n");
      out.write("                        modal.style.visibility = 'visible';\n");
      out.write("                        modal.style.opacity = '1';\n");
      out.write("                        modal.style.position = 'fixed';\n");
      out.write("                        modal.style.zIndex = '99999';\n");
      out.write("                        modal.style.left = '0';\n");
      out.write("                        modal.style.top = '0';\n");
      out.write("                        modal.style.width = '100%';\n");
      out.write("                        modal.style.height = '100%';\n");
      out.write("                        modal.style.backgroundColor = 'rgba(0, 0, 0, 0.7)';\n");
      out.write("                        document.body.style.overflow = 'hidden';\n");
      out.write("                        return;\n");
      out.write("                    }\n");
      out.write("                    \n");
      out.write("                    // If modal doesn't exist, find the form and create modal\n");
      out.write("                    var formDiv = document.getElementById('auctionFillOutForm');\n");
      out.write("                    if (!formDiv) {\n");
      out.write("                        // Try to find it by class\n");
      out.write("                        formDiv = document.querySelector('.auction-form');\n");
      out.write("                    }\n");
      out.write("                    \n");
      out.write("                    if (!formDiv) {\n");
      out.write("                        alert('Form not found! Please refresh the page.');\n");
      out.write("                        console.error('Could not find auctionFillOutForm or .auction-form');\n");
      out.write("                        return;\n");
      out.write("                    }\n");
      out.write("                    \n");
      out.write("                    // Create modal dynamically\n");
      out.write("                    modal = document.createElement('div');\n");
      out.write("                    modal.id = 'createAuctionModal';\n");
      out.write("                    modal.className = 'modal';\n");
      out.write("                    modal.style.cssText = 'display: block; position: fixed; z-index: 99999; left: 0; top: 0; width: 100%; height: 100%; overflow: auto; background-color: rgba(0, 0, 0, 0.7);';\n");
      out.write("                    \n");
      out.write("                    var modalContent = document.createElement('div');\n");
      out.write("                    modalContent.className = 'modal-content';\n");
      out.write("                    modalContent.style.cssText = 'background-color: white; margin: 5% auto; padding: 0; border-radius: 12px; width: 90%; max-width: 900px; max-height: 85vh; overflow-y: auto; box-shadow: 0 10px 25px rgba(0,0,0,0.15); position: relative;';\n");
      out.write("                    \n");
      out.write("                    var closeBtn = document.createElement('span');\n");
      out.write("                    closeBtn.className = 'modal-close';\n");
      out.write("                    closeBtn.innerHTML = '&times;';\n");
      out.write("                    closeBtn.onclick = closeAuctionModal;\n");
      out.write("                    closeBtn.style.cssText = 'color: #7f8c8d; float: right; font-size: 32px; font-weight: bold; position: absolute; right: 20px; top: 15px; z-index: 10001; cursor: pointer; line-height: 1;';\n");
      out.write("                    \n");
      out.write("                    modalContent.appendChild(closeBtn);\n");
      out.write("                    modalContent.appendChild(formDiv.cloneNode(true));\n");
      out.write("                    modal.appendChild(modalContent);\n");
      out.write("                    \n");
      out.write("                    // Close on background click\n");
      out.write("                    modal.onclick = function(e) {\n");
      out.write("                        if (e.target === modal) {\n");
      out.write("                            closeAuctionModal();\n");
      out.write("                        }\n");
      out.write("                    };\n");
      out.write("                    \n");
      out.write("                    document.body.appendChild(modal);\n");
      out.write("                    document.body.style.overflow = 'hidden';\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                function closeAuctionModal() {\n");
      out.write("                    var modal = document.getElementById('createAuctionModal');\n");
      out.write("                    if (modal) {\n");
      out.write("                        modal.classList.remove('show');\n");
      out.write("                        modal.style.cssText = 'display: none !important;';\n");
      out.write("                        document.body.style.overflow = \"auto\";\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                function toggleSearch() {\n");
      out.write("                    console.log('toggleSearch function called');\n");
      out.write("                    var searchDiv = document.getElementById('searchSection');\n");
      out.write("                    var formDiv = document.getElementById('auctionFillOutForm');\n");
      out.write("                    \n");
      out.write("                    if (searchDiv) {\n");
      out.write("                        var currentDisplay = window.getComputedStyle(searchDiv).display;\n");
      out.write("                        if (currentDisplay === \"none\") {\n");
      out.write("                            // Show search section\n");
      out.write("                            searchDiv.style.display = \"block\";\n");
      out.write("                            // Hide auction form if it's visible\n");
      out.write("                            if (formDiv) {\n");
      out.write("                                formDiv.style.display = \"none\";\n");
      out.write("                            }\n");
      out.write("                        } else {\n");
      out.write("                            // Hide search section\n");
      out.write("                            searchDiv.style.display = \"none\";\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                    return false;\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("        </head>\n");
      out.write("        <body>\n");
      out.write("            <!-- Header -->\n");
      out.write("            <header class=\"header\">\n");
      out.write("                <div class=\"header-container\">\n");
      out.write("                    <a href=\"mainPage.jsp\" class=\"logo\">🏛️ ThriftShop</a>\n");
      out.write("            <nav>\n");
      out.write("                        <ul class=\"nav-menu\">\n");
      out.write("                    <li><a href=\"tops.jsp\">Tops</a></li>\n");
      out.write("                    <li><a href=\"bottoms.jsp\">Bottoms</a></li>\n");
      out.write("                    <li><a href=\"shoes.jsp\">Shoes</a></li>\n");
      out.write("                    <li><a href=\"sellers.jsp\">Sellers</a></li>\n");
      out.write("                    <li><a href=\"notifications.jsp\">Notifications</a></li>\n");
      out.write("                    <li><a href=\"profile.jsp\">Profile</a></li>\n");
      out.write("                            <li><a href=\"../LoginPage/logout.jsp\">Logout</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("                    <div class=\"user-info\">👤 ");
      out.print(session.getAttribute("username"));
      out.write("</div>\n");
      out.write("                </div>\n");
      out.write("            </header>\n");
      out.write("\n");
      out.write("            <!-- Main Content -->\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"page-header\">\n");
      out.write("                    <h1>Welcome to ThriftShop</h1>\n");
      out.write("                    <p>Your premium auction marketplace for quality clothing</p>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Action Buttons -->\n");
      out.write("                <div style=\"display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap;\">\n");
      out.write("                    <button type=\"button\" id=\"searchBtn\" class=\"btn btn-secondary\" style=\"cursor: pointer; min-width: 150px; color: white;\">🔍 Search Items</button>\n");
      out.write("                    <button type=\"button\" id=\"createAuctionBtn\" onclick=\"createAuction(); return false;\" class=\"btn btn-primary\" style=\"cursor: pointer; min-width: 150px; color: #1a1f3a; font-weight: 600;\">➕ Create Auction</button>\n");
      out.write("                </div>\n");
      out.write("            <script>\n");
      out.write("                document.addEventListener(\"DOMContentLoaded\", function () {\n");
      out.write("                    // Add event listeners to buttons\n");
      out.write("                    var createAuctionBtn = document.getElementById('createAuctionBtn');\n");
      out.write("                    if (createAuctionBtn) {\n");
      out.write("                        createAuctionBtn.onclick = function(e) {\n");
      out.write("                            e.preventDefault();\n");
      out.write("                            createAuction();\n");
      out.write("                            return false;\n");
      out.write("                        };\n");
      out.write("                    }\n");
      out.write("                    \n");
      out.write("                    // Close modal when clicking outside\n");
      out.write("                    var modal = document.getElementById('createAuctionModal');\n");
      out.write("                    if (modal) {\n");
      out.write("                        modal.onclick = function(e) {\n");
      out.write("                            if (e.target === modal) {\n");
      out.write("                                closeAuctionModal();\n");
      out.write("                            }\n");
      out.write("                        };\n");
      out.write("                    }\n");
      out.write("                    \n");
      out.write("                    // Close modal with Escape key\n");
      out.write("                    document.addEventListener('keydown', function(e) {\n");
      out.write("                        if (e.key === 'Escape') {\n");
      out.write("                            closeAuctionModal();\n");
      out.write("                        }\n");
      out.write("                    });\n");
      out.write("                    \n");
      out.write("                    var searchBtn = document.getElementById('searchBtn');\n");
      out.write("                    if (searchBtn) {\n");
      out.write("                        searchBtn.addEventListener('click', function(e) {\n");
      out.write("                            e.preventDefault();\n");
      out.write("                            toggleSearch();\n");
      out.write("                        }, false);\n");
      out.write("                    }\n");
      out.write("                    \n");
      out.write("                    // Search Form Toggling\n");
      out.write("                    var searchTypeSelect = document.getElementById('searchTypeSelect');\n");
      out.write("                    if (searchTypeSelect) {\n");
      out.write("                        searchTypeSelect.addEventListener(\"change\", function () {\n");
      out.write("                        const value = this.value;\n");
      out.write("                        const forms = ['searchFormTops', 'searchFormBottoms', 'searchFormShoes', 'searchFormAny'];\n");
      out.write("                        const buttons = ['searchTopSubmit', 'searchBottomSubmit', 'searchShoeSubmit', 'searchAnySubmit'];\n");
      out.write("\n");
      out.write("                        forms.forEach(id => {\n");
      out.write("                            const el = document.getElementById(id);\n");
      out.write("                            if (el) el.style.display = 'none';\n");
      out.write("                        });\n");
      out.write("                        buttons.forEach(id => {\n");
      out.write("                            const el = document.getElementById(id);\n");
      out.write("                            if (el) el.style.display = 'none';\n");
      out.write("                        });\n");
      out.write("\n");
      out.write("                        if (value === \"tops\") {\n");
      out.write("                            document.getElementById('searchFormTops').style.display = \"block\";\n");
      out.write("                            document.getElementById('searchTopSubmit').style.display = \"block\";\n");
      out.write("                        } else if (value === \"bottoms\") {\n");
      out.write("                            document.getElementById('searchFormBottoms').style.display = \"block\";\n");
      out.write("                            document.getElementById('searchBottomSubmit').style.display = \"block\";\n");
      out.write("                        } else if (value === \"shoes\") {\n");
      out.write("                            document.getElementById('searchFormShoes').style.display = \"block\";\n");
      out.write("                            document.getElementById('searchShoeSubmit').style.display = \"block\";\n");
      out.write("                        } else if (value === \"any\") {\n");
      out.write("                            document.getElementById('searchFormAny').style.display = \"block\";\n");
      out.write("                            document.getElementById('searchAnySubmit').style.display = \"block\";\n");
      out.write("                        }\n");
      out.write("                    });\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    // Create Auction Form Toggling\n");
      out.write("                    var itemsTypeSelect = document.getElementById('itemsTypeSelect');\n");
      out.write("                    if (itemsTypeSelect) {\n");
      out.write("                        itemsTypeSelect.addEventListener(\"change\", function () {\n");
      out.write("                        const value = this.value;\n");
      out.write("\n");
      out.write("                        if (value === \"tops\") {\n");
      out.write("                            document.getElementById('auctionFillOutFormTops').style.display = \"block\";\n");
      out.write("                            document.getElementById('auctionFillOutFormBottoms').style.display = \"none\";\n");
      out.write("                            document.getElementById('auctionFillOutFormShoes').style.display = \"none\";\n");
      out.write("                            document.getElementById('TopSubmit').style.display = \"block\";\n");
      out.write("                            document.getElementById('BottomSubmit').style.display = \"none\";\n");
      out.write("                            document.getElementById('ShoeSubmit').style.display = \"none\";\n");
      out.write("                        }\n");
      out.write("                        if (value === \"bottoms\") {\n");
      out.write("                            document.getElementById('auctionFillOutFormBottoms').style.display = \"block\";\n");
      out.write("                            document.getElementById('auctionFillOutFormTops').style.display = \"none\";\n");
      out.write("                            document.getElementById('auctionFillOutFormShoes').style.display = \"none\";\n");
      out.write("                            document.getElementById('BottomSubmit').style.display = \"block\";\n");
      out.write("                            document.getElementById('TopSubmit').style.display = \"none\";\n");
      out.write("                            document.getElementById('ShoeSubmit').style.display = \"none\";\n");
      out.write("                        }\n");
      out.write("                        if (value === \"shoes\") {\n");
      out.write("                            document.getElementById('auctionFillOutFormShoes').style.display = \"block\";\n");
      out.write("                            document.getElementById('auctionFillOutFormTops').style.display = \"none\";\n");
      out.write("                            document.getElementById('auctionFillOutFormBottoms').style.display = \"none\";\n");
      out.write("                            document.getElementById('ShoeSubmit').style.display = \"block\";\n");
      out.write("                            document.getElementById('TopSubmit').style.display = \"none\";\n");
      out.write("                            document.getElementById('BottomSubmit').style.display = \"none\";\n");
      out.write("                        }\n");
      out.write("                        });\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("            </script>\n");
      out.write("\n");
      out.write("                <!-- Search Section -->\n");
      out.write("                <div id=\"searchSection\" class=\"search-section\" style=\"display:none;\">\n");
      out.write("                    <div class=\"card-header\">\n");
      out.write("                        <h2 class=\"card-title\">🔍 Search Items</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"searchType\">Choose Item Type to Search</label>\n");
      out.write("                        <select name=\"searchType\" id=\"searchTypeSelect\" class=\"form-control\">\n");
      out.write("                    <option value=\"selectAnItem\" disabled selected>Select Item...</option>\n");
      out.write("                    <option value=\"any\">Any Item Type</option>\n");
      out.write("                    <option value=\"tops\">Tops</option>\n");
      out.write("                    <option value=\"bottoms\">Bottoms</option>\n");
      out.write("                    <option value=\"shoes\">Shoes</option>\n");
      out.write("                </select>\n");
      out.write("\n");
      out.write("                <!-- Any item type search form -->\n");
      out.write("                <form action=\"searchResults.jsp\" method=\"POST\">\n");
      out.write("                    <input type=\"hidden\" name=\"itemType\" value=\"any\">\n");
      out.write("                    <div id=\"searchFormAny\" class=\"form-row\" style=\"display: none;\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Seller Username</label>\n");
      out.write("                            <input type=\"text\" name=\"searchSeller\" class=\"form-control\" placeholder=\"Any seller\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Gender</label>\n");
      out.write("                            <select name=\"searchGender\" class=\"form-control\">\n");
      out.write("                            <option value=\"\" selected>Any Gender</option>\n");
      out.write("                            <option value=\"Male\">Male</option>\n");
      out.write("                            <option value=\"Female\">Female</option>\n");
      out.write("                            <option value=\"Unisex\">Unisex</option>\n");
      out.write("                        </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Size</label>\n");
      out.write("                            <input type=\"text\" name=\"searchSize\" class=\"form-control\" placeholder=\"Any Size\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Color</label>\n");
      out.write("                            <select name=\"searchColor\" class=\"form-control\">\n");
      out.write("                            <option value=\"\" selected>Any Color</option>\n");
      out.write("                            <option value=\"Black\">Black</option>\n");
      out.write("                            <option value=\"Blue\">Blue</option>\n");
      out.write("                            <option value=\"Gray\">Gray</option>\n");
      out.write("                            <option value=\"White\">White</option>\n");
      out.write("                            <option value=\"Brown\">Brown</option>\n");
      out.write("                            <option value=\"Red\">Red</option>\n");
      out.write("                            <option value=\"Pink\">Pink</option>\n");
      out.write("                            <option value=\"Orange\">Orange</option>\n");
      out.write("                            <option value=\"Yellow\">Yellow</option>\n");
      out.write("                            <option value=\"Green\">Green</option>\n");
      out.write("                            <option value=\"Purple\">Purple</option>\n");
      out.write("                        </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Description contains</label>\n");
      out.write("                            <input type=\"text\" name=\"searchDescription\" class=\"form-control\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Condition</label>\n");
      out.write("                            <input type=\"text\" name=\"searchCondition\" class=\"form-control\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Min Price</label>\n");
      out.write("                            <input type=\"number\" name=\"searchMinPrice\" class=\"form-control\" min=\"0\" step=\"0.01\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Max Price</label>\n");
      out.write("                            <input type=\"number\" name=\"searchMaxPrice\" class=\"form-control\" min=\"0\" step=\"0.01\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" id=\"searchAnySubmit\" style=\"display: none; width: 100%;\">Search All Items</button>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                <!-- Tops search form -->\n");
      out.write("                <form action=\"searchResults.jsp\" method=\"POST\">\n");
      out.write("                    <input type=\"hidden\" name=\"itemType\" value=\"tops\">\n");
      out.write("                    <div id=\"searchFormTops\" class=\"form-row\" style=\"display: none;\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Seller Username</label>\n");
      out.write("                            <input type=\"text\" name=\"searchSeller\" class=\"form-control\" placeholder=\"Any seller\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Gender</label>\n");
      out.write("                            <select name=\"searchTopGender\" class=\"form-control\">\n");
      out.write("                            <option value=\"\" selected>Any Gender</option>\n");
      out.write("                            <option value=\"Male\">Male</option>\n");
      out.write("                            <option value=\"Female\">Female</option>\n");
      out.write("                            <option value=\"Unisex\">Unisex</option>\n");
      out.write("                        </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Top Size</label>\n");
      out.write("                            <select name=\"searchTopSize\" class=\"form-control\">\n");
      out.write("                            <option value=\"\" selected>Any Size</option>\n");
      out.write("                            <option value=\"XS\">XS</option>\n");
      out.write("                            <option value=\"S\">S</option>\n");
      out.write("                            <option value=\"M\">M</option>\n");
      out.write("                            <option value=\"L\">L</option>\n");
      out.write("                            <option value=\"XL\">XL</option>\n");
      out.write("                            <option value=\"XXL\">XXL</option>\n");
      out.write("                            <option value=\"3XL\">3XL</option>\n");
      out.write("                        </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Color</label>\n");
      out.write("                            <select name=\"searchTopColor\" class=\"form-control\">\n");
      out.write("                            <option value=\"\" selected>Any Color</option>\n");
      out.write("                            <option value=\"Black\">Black</option>\n");
      out.write("                            <option value=\"Blue\">Blue</option>\n");
      out.write("                            <option value=\"Gray\">Gray</option>\n");
      out.write("                            <option value=\"White\">White</option>\n");
      out.write("                            <option value=\"Brown\">Brown</option>\n");
      out.write("                            <option value=\"Red\">Red</option>\n");
      out.write("                            <option value=\"Pink\">Pink</option>\n");
      out.write("                            <option value=\"Orange\">Orange</option>\n");
      out.write("                            <option value=\"Yellow\">Yellow</option>\n");
      out.write("                            <option value=\"Green\">Green</option>\n");
      out.write("                            <option value=\"Purple\">Purple</option>\n");
      out.write("                        </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Front Length (cm)</label>\n");
      out.write("                            <input type=\"number\" name=\"searchTopFrontLength\" class=\"form-control\" min=\"0\" step=\"0.1\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Chest Length (cm)</label>\n");
      out.write("                            <input type=\"number\" name=\"searchTopChestLength\" class=\"form-control\" min=\"0\" step=\"0.1\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Sleeve Length (cm)</label>\n");
      out.write("                            <input type=\"number\" name=\"searchTopSleeveLength\" class=\"form-control\" min=\"0\" step=\"0.1\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Description</label>\n");
      out.write("                            <input type=\"text\" name=\"searchTopDescription\" class=\"form-control\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Condition</label>\n");
      out.write("                            <input type=\"text\" name=\"searchTopCondition\" class=\"form-control\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Min Price</label>\n");
      out.write("                            <input type=\"number\" name=\"searchMinPrice\" class=\"form-control\" min=\"0\" step=\"0.01\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Max Price</label>\n");
      out.write("                            <input type=\"number\" name=\"searchMaxPrice\" class=\"form-control\" min=\"0\" step=\"0.01\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" id=\"searchTopSubmit\" style=\"display: none; width: 100%;\">Search Tops</button>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                <!-- Bottoms search form -->\n");
      out.write("                <form action=\"searchResults.jsp\" method=\"POST\">\n");
      out.write("                    <input type=\"hidden\" name=\"itemType\" value=\"bottoms\">\n");
      out.write("                    <div id=\"searchFormBottoms\" style=\"display: none;\">\n");
      out.write("                        <label>Seller Username:</label> <input type=\"text\" name=\"searchSeller\" placeholder=\"Any seller\">\n");
      out.write("                        <label>Gender: </label>\n");
      out.write("                        <select name=\"searchBottomGender\">\n");
      out.write("                            <option value=\"\" selected>Any Gender</option>\n");
      out.write("                            <option value=\"Male\">Male</option>\n");
      out.write("                            <option value=\"Female\">Female</option>\n");
      out.write("                            <option value=\"Unisex\">Unisex</option>\n");
      out.write("                        </select>\n");
      out.write("                        <label>Bottom Size: </label>\n");
      out.write("                        <select name=\"searchBottomSize\">\n");
      out.write("                            <option value=\"\" selected>Any Size</option>\n");
      out.write("                            <option value=\"XS\">XS</option>\n");
      out.write("                            <option value=\"S\">S</option>\n");
      out.write("                            <option value=\"M\">M</option>\n");
      out.write("                            <option value=\"L\">L</option>\n");
      out.write("                            <option value=\"XL\">XL</option>\n");
      out.write("                            <option value=\"XXL\">XXL</option>\n");
      out.write("                            <option value=\"3XL\">3XL</option>\n");
      out.write("                        </select>\n");
      out.write("                        <label>Color: </label>\n");
      out.write("                        <select name=\"searchBottomColor\">\n");
      out.write("                            <option value=\"\" selected>Any Color</option>\n");
      out.write("                            <option value=\"Black\">Black</option>\n");
      out.write("                            <option value=\"Blue\">Blue</option>\n");
      out.write("                            <option value=\"Gray\">Gray</option>\n");
      out.write("                            <option value=\"White\">White</option>\n");
      out.write("                            <option value=\"Brown\">Brown</option>\n");
      out.write("                            <option value=\"Red\">Red</option>\n");
      out.write("                            <option value=\"Pink\">Pink</option>\n");
      out.write("                            <option value=\"Orange\">Orange</option>\n");
      out.write("                            <option value=\"Yellow\">Yellow</option>\n");
      out.write("                            <option value=\"Green\">Green</option>\n");
      out.write("                            <option value=\"Purple\">Purple</option>\n");
      out.write("                        </select>\n");
      out.write("            <label>Waist Length (cm): </label> <input type=\"number\" name=\"searchBottomWaistLength\" min=\"0\" step=\"0.1\">\n");
      out.write("            <label>Inseam Length (cm): </label> <input type=\"number\" name=\"searchBottomInseamLength\" min=\"0\" step=\"0.1\">\n");
      out.write("            <label>Outseam Length (cm): </label> <input type=\"number\" name=\"searchBottomOutseamLength\" min=\"0\" step=\"0.1\">\n");
      out.write("            <label>Hip Length (cm): </label> <input type=\"number\" name=\"searchBottomHipLength\" min=\"0\" step=\"0.1\">\n");
      out.write("            <label>Rise Length (cm): </label> <input type=\"number\" name=\"searchBottomRiseLength\" min=\"0\" step=\"0.1\">\n");
      out.write("                        <label>Description: </label> <input type=\"text\" name=\"searchBottomDescription\">\n");
      out.write("                        <label>Condition: </label> <input type=\"text\" name=\"searchBottomCondition\">\n");
      out.write("                        <label>Min Price:</label> <input type=\"number\" name=\"searchMinPrice\" min=\"0\">\n");
      out.write("                        <label>Max Price:</label> <input type=\"number\" name=\"searchMaxPrice\" min=\"0\">\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" id=\"searchBottomSubmit\" style=\"display: none; width: 100%;\">Search Bottoms</button>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                <!-- Shoes search form -->\n");
      out.write("                <form action=\"searchResults.jsp\" method=\"POST\">\n");
      out.write("                    <input type=\"hidden\" name=\"itemType\" value=\"shoes\">\n");
      out.write("                    <div id=\"searchFormShoes\" class=\"form-row\" style=\"display: none;\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Seller Username</label>\n");
      out.write("                            <input type=\"text\" name=\"searchSeller\" class=\"form-control\" placeholder=\"Any seller\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Gender</label>\n");
      out.write("                            <select name=\"searchShoeGender\" class=\"form-control\">\n");
      out.write("                            <option value=\"\" selected>Any Gender</option>\n");
      out.write("                            <option value=\"Male\">Male</option>\n");
      out.write("                            <option value=\"Female\">Female</option>\n");
      out.write("                            <option value=\"Unisex\">Unisex</option>\n");
      out.write("                        </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Shoe Size</label>\n");
      out.write("                            <select name=\"searchShoeSize\" class=\"form-control\">\n");
      out.write("                            <option value=\"\" selected>Any Size</option>\n");
      out.write("                            ");
 for (int i = 1; i <= 23; i++) { 
      out.write("\n");
      out.write("                <option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Color</label>\n");
      out.write("                            <select name=\"searchShoeColor\" class=\"form-control\">\n");
      out.write("                            <option value=\"\" selected>Any Color</option>\n");
      out.write("                            <option value=\"Black\">Black</option>\n");
      out.write("                            <option value=\"Blue\">Blue</option>\n");
      out.write("                            <option value=\"Gray\">Gray</option>\n");
      out.write("                            <option value=\"White\">White</option>\n");
      out.write("                            <option value=\"Brown\">Brown</option>\n");
      out.write("                            <option value=\"Red\">Red</option>\n");
      out.write("                            <option value=\"Pink\">Pink</option>\n");
      out.write("                            <option value=\"Orange\">Orange</option>\n");
      out.write("                            <option value=\"Yellow\">Yellow</option>\n");
      out.write("                            <option value=\"Green\">Green</option>\n");
      out.write("                            <option value=\"Purple\">Purple</option>\n");
      out.write("                        </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Description</label>\n");
      out.write("                            <input type=\"text\" name=\"searchShoeDescription\" class=\"form-control\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Condition</label>\n");
      out.write("                            <input type=\"text\" name=\"searchShoeCondition\" class=\"form-control\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Min Price</label>\n");
      out.write("                            <input type=\"number\" name=\"searchMinPrice\" class=\"form-control\" min=\"0\" step=\"0.01\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>Max Price</label>\n");
      out.write("                            <input type=\"number\" name=\"searchMaxPrice\" class=\"form-control\" min=\"0\" step=\"0.01\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" id=\"searchShoeSubmit\" style=\"display: none; width: 100%;\">Search Shoes</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("                <!-- Create Auction Modal -->\n");
      out.write("                <div id=\"createAuctionModal\" class=\"modal\" style=\"display: none;\">\n");
      out.write("                    <div class=\"modal-content\">\n");
      out.write("                        <span class=\"modal-close\" onclick=\"closeAuctionModal()\">&times;</span>\n");
      out.write("                        <div id=\"auctionFillOutForm\" class=\"auction-form\">\n");
      out.write("                    <div class=\"card-header\">\n");
      out.write("                        <h2 class=\"card-title\">➕ Create New Auction</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"itemsType\">Choose Item Type</label>\n");
      out.write("                        <select name=\"itemsType\" id=\"itemsTypeSelect\" class=\"form-control\" required>\n");
      out.write("                    <option value=\"selectAnItem\" disabled selected>Select Item...</option>\n");
      out.write("                    <option value=\"tops\" id=\"tops\">Tops</option>\n");
      out.write("                    <option value=\"bottoms\" id=\"bottoms\">Bottoms</option>\n");
      out.write("                    <option value=\"shoes\" id=\"shoes\">Shoes</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("                <form action=\"../tops\" method=\"POST\" enctype=\"multipart/form-data\">\n");
      out.write("                    <div id=\"auctionFillOutFormTops\" class=\"form-row\" style=\"display: none;\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"topGender\">Gender</label>\n");
      out.write("                            <select name=\"topGender\" id=\"topsGenderLabel\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Gender...</option>\n");
      out.write("                        <option value=\"Male\">Male</option>\n");
      out.write("                        <option value=\"Female\">Female</option>\n");
      out.write("                        <option value=\"Unisex\">Unisex</option>\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"topSize\">Top Size</label>\n");
      out.write("                            <select name=\"topSize\" id=\"topSizeSelect\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Size...</option>\n");
      out.write("                        <option value=\"XS\">XS</option>\n");
      out.write("                        <option value=\"S\">S</option>\n");
      out.write("                        <option value=\"M\">M</option>\n");
      out.write("                        <option value=\"L\">L</option>\n");
      out.write("                        <option value=\"XL\">XL</option>\n");
      out.write("                        <option value=\"XXL\">XXL</option>\n");
      out.write("                        <option value=\"3XL\">3XL</option>\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"topColor\">Color</label>\n");
      out.write("                            <select name=\"topColor\" id=\"TopColorColor\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Color...</option>\n");
      out.write("                        <option value=\"Black\">Black</option>\n");
      out.write("                        <option value=\"Blue\">Blue</option>\n");
      out.write("                        <option value=\"Gray\">Gray</option>\n");
      out.write("                        <option value=\"White\">White</option>\n");
      out.write("                        <option value=\"Brown\">Brown</option>\n");
      out.write("                        <option value=\"Red\">Red</option>\n");
      out.write("                        <option value=\"Pink\">Pink</option>\n");
      out.write("                        <option value=\"Orange\">Orange</option>\n");
      out.write("                        <option value=\"Yellow\">Yellow</option>\n");
      out.write("                        <option value=\"Green\">Green</option>\n");
      out.write("                        <option value=\"Purple\">Purple</option>\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"FrontLength\">Front Length (cm)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"FrontLength\" id=\"FrontLengthTop\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"ChestLength\">Chest Length (cm)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"ChestLength\" id=\"ChestLengthTop\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"SleeveLength\">Sleeve Length (cm)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"SleeveLength\" id=\"SleeveLengthTop\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Description\">Description</label>\n");
      out.write("                            <input name=\"Description\" id=\"DescriptionTop\" class=\"form-control\" maxLength=\"200\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Condition\">Condition</label>\n");
      out.write("                            <input name=\"Condition\" id=\"ConditionTop\" class=\"form-control\" maxLength=\"200\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Minimum\">Reserve Price (USD) - Hidden from buyers</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"Minimum\" id=\"MinimumBidConditionTop\" class=\"form-control\" step=\"0.01\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"StartingOrCurrentBidPrice\">Starting Bid Price (USD)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"StartingOrCurrentBidPrice\" id=\"StartingOrCurrentBidPriceTop\" class=\"form-control\" step=\"0.01\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"AuctionCloseDateTops\">Auction Close Date</label>\n");
      out.write("                            <input type=\"date\" name=\"AuctionCloseDateTops\" id=\"AuctionCloseTopsDate\" class=\"form-control\" required min=\"");
      out.print(today);
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"AuctionCloseTime\">Auction Close Time</label>\n");
      out.write("                            <input type=\"time\" name=\"AuctionCloseTimeTops\" id=\"AuctionCloseTopsTime\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"image\">Item Image (optional)</label>\n");
      out.write("                            <input type=\"file\" name=\"image\" id=\"imageTop\" class=\"form-control\" accept=\"image/*\">\n");
      out.write("                        </div>\n");
      out.write("                </div>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" id=\"TopSubmit\" style=\"display: none; width: 100%;\">Create Auction</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <form action=\"bottoms.jsp\" method=\"POST\">\n");
      out.write("                    <div id=\"auctionFillOutFormBottoms\" class=\"form-row\" style=\"display: none;\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"bottomGender\">Gender</label>\n");
      out.write("                            <select name=\"bottomGender\" id=\"bottomGenderSelect\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Gender...</option>\n");
      out.write("                        <option value=\"Male\">Male</option>\n");
      out.write("                        <option value=\"Female\">Female</option>\n");
      out.write("                        <option value=\"Unisex\">Unisex</option>\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"bottomSize\">Bottom Size</label>\n");
      out.write("                            <select name=\"bottomSize\" id=\"bottomSizeSelect\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Size...</option>\n");
      out.write("                        <option value=\"XS\">XS</option>\n");
      out.write("                        <option value=\"S\">S</option>\n");
      out.write("                        <option value=\"M\">M</option>\n");
      out.write("                        <option value=\"L\">L</option>\n");
      out.write("                        <option value=\"XL\">XL</option>\n");
      out.write("                        <option value=\"XXL\">XXL</option>\n");
      out.write("                        <option value=\"3XL\">3XL</option>\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"bottomColor\">Color</label>\n");
      out.write("                            <select name=\"bottomColor\" id=\"bottomColorColor\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Color...</option>\n");
      out.write("                        <option value=\"Black\">Black</option>\n");
      out.write("                        <option value=\"Blue\">Blue</option>\n");
      out.write("                        <option value=\"Gray\">Gray</option>\n");
      out.write("                        <option value=\"White\">White</option>\n");
      out.write("                        <option value=\"Brown\">Brown</option>\n");
      out.write("                        <option value=\"Red\">Red</option>\n");
      out.write("                        <option value=\"Pink\">Pink</option>\n");
      out.write("                        <option value=\"Orange\">Orange</option>\n");
      out.write("                        <option value=\"Yellow\">Yellow</option>\n");
      out.write("                        <option value=\"Green\">Green</option>\n");
      out.write("                        <option value=\"Purple\">Purple</option>\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"WaistLength\">Waist Length (cm)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"WaistLength\" id=\"WaistLengthBottom\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"InseamLength\">Inseam Length (cm)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"InseamLength\" id=\"InseamLengthBottom\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"OutseamLength\">Outseam Length (cm)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"OutseamLength\" id=\"OutseamLengthBottom\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"HipLength\">Hip Length (cm)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"HipLength\" id=\"HipLengthBottom\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"RiseLength\">Rise Length (cm)</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"RiseLength\" id=\"RiseLengthBottom\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Description\">Description</label>\n");
      out.write("                            <input name=\"Description\" id=\"DescriptionBottom\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Condition\">Condition</label>\n");
      out.write("                            <input name=\"Condition\" id=\"ConditionBottom\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Minimum\">Reserve Price (USD) - Hidden from buyers</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"Minimum\" id=\"MinimumBidConditionBottom\" class=\"form-control\" step=\"0.01\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"AuctionCloseDateBottoms\">Auction Close Date</label>\n");
      out.write("                            <input type=\"date\" name=\"AuctionCloseDateBottoms\" id=\"AuctionCloseBottomsDate\" class=\"form-control\" min=\"");
      out.print(today);
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"AuctionCloseTimeBottoms\">Auction Close Time</label>\n");
      out.write("                            <input type=\"time\" name=\"AuctionCloseTimeBottoms\" id=\"AuctionCloseBottomsTime\" class=\"form-control\">\n");
      out.write("                        </div>\n");
      out.write("                </div>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" id=\"BottomSubmit\" style=\"display: none; width: 100%;\">Create Auction</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <form action=\"shoes.jsp\" method=\"POST\">\n");
      out.write("                    <div id=\"auctionFillOutFormShoes\" class=\"form-row\" style=\"display: none;\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"shoeGender\">Gender</label>\n");
      out.write("                            <select name=\"shoeGender\" id=\"shoeGenderSelect\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Gender...</option>\n");
      out.write("                        <option value=\"Male\">Male</option>\n");
      out.write("                        <option value=\"Female\">Female</option>\n");
      out.write("                        <option value=\"Unisex\">Unisex</option>\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"shoeSize\">Shoe Size</label>\n");
      out.write("                            <select name=\"shoeSize\" id=\"shoeSizeSelect\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Size...</option>\n");
      out.write("                                ");
 for (int i = 1; i <= 23; i++) { 
      out.write("\n");
      out.write("                                <option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"shoeColor\">Color</label>\n");
      out.write("                            <select name=\"shoeColor\" id=\"ShoeColorColor\" class=\"form-control\" required>\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Color...</option>\n");
      out.write("                        <option value=\"Black\">Black</option>\n");
      out.write("                        <option value=\"Blue\">Blue</option>\n");
      out.write("                        <option value=\"Gray\">Gray</option>\n");
      out.write("                        <option value=\"White\">White</option>\n");
      out.write("                        <option value=\"Brown\">Brown</option>\n");
      out.write("                        <option value=\"Red\">Red</option>\n");
      out.write("                        <option value=\"Pink\">Pink</option>\n");
      out.write("                        <option value=\"Orange\">Orange</option>\n");
      out.write("                        <option value=\"Yellow\">Yellow</option>\n");
      out.write("                        <option value=\"Green\">Green</option>\n");
      out.write("                        <option value=\"Purple\">Purple</option>\n");
      out.write("                    </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Description\">Description</label>\n");
      out.write("                            <input maxlength=\"200\" name=\"Description\" id=\"DescriptionShoe\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Condition\">Condition</label>\n");
      out.write("                            <input maxlength=\"200\" name=\"Condition\" id=\"ConditionShoe\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"Minimum\">Reserve Price (USD) - Hidden from buyers</label>\n");
      out.write("                            <input type=\"number\" min=\"0\" name=\"Minimum\" id=\"MinimumBidConditionShoe\" class=\"form-control\" step=\"0.01\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"AuctionCloseDateShoes\">Auction Close Date</label>\n");
      out.write("                            <input type=\"date\" name=\"AuctionCloseDateShoes\" id=\"AuctionCloseShoesDate\" class=\"form-control\" min=\"");
      out.print(today);
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"AuctionCloseTimeShoes\">Auction Close Time</label>\n");
      out.write("                            <input type=\"time\" name=\"AuctionCloseTimeShoes\" id=\"AuctionCloseShoesTime\" class=\"form-control\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" id=\"ShoeSubmit\" style=\"display: none; width: 100%;\">Create Auction</button>\n");
      out.write("                </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        </body>\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
