/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-07 00:10:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import java.sql.*;

public final class notifications_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // check login
    if (session.getAttribute("username") == null) {
        response.sendRedirect("../LoginPage/login.jsp");
        return;
    }

    String username = (String) session.getAttribute("username");

    Class.forName("com.mysql.cj.jdbc.Driver");
    String jdbcUrl = System.getenv("JDBC_URL");
    if (jdbcUrl == null || jdbcUrl.isEmpty()) {
        String dbHost = System.getenv("DB_HOST");
        String dbPort = System.getenv("DB_PORT");
        String dbName = System.getenv("DB_NAME");
        if (dbHost == null) dbHost = "localhost";
        if (dbPort == null) dbPort = "3306";
        if (dbName == null) dbName = "thriftShop";
        jdbcUrl = "jdbc:mysql://" + dbHost + ":" + dbPort + "/" + dbName;
    }
    String dbUser = System.getenv("DB_USER");
    if (dbUser == null) dbUser = "root";
    String dbPass = System.getenv("DB_PASS");
    if (dbPass == null) dbPass = "12345";
    Connection con = DriverManager.getConnection(jdbcUrl, dbUser, dbPass);

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Bid Notifications</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h3>User: ");
      out.print( username );
      out.write("</h3>\n");
      out.write("<a href=\"mainPage.jsp\">Back to Main Page</a>\n");
      out.write("<hr/>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function createBid(counter) {\n");
      out.write("        var SetNewBidLabel = document.getElementById('SetNewBidLabel' + counter);\n");
      out.write("        var SetNewBid = document.getElementById('SetNewBid' + counter);\n");
      out.write("        var SetAutomaticBidLabel = document.getElementById('SetAutomaticBidLabel' + counter);\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("        var cancel = document.getElementById('cancel' + counter);\n");
      out.write("        var PlaceBid = document.getElementById('TopPlaceBid' + counter);\n");
      out.write("\n");
      out.write("        SetNewBidLabel.style.display = 'block';\n");
      out.write("        SetNewBid.style.display = 'block';\n");
      out.write("        SetAutomaticBidLabel.style.display = 'block';\n");
      out.write("        SetAutomaticBid.style.display = 'block';\n");
      out.write("        cancel.style.display = 'block';\n");
      out.write("        PlaceBid.style.display = 'block';\n");
      out.write("\n");
      out.write("        SetAutomaticBid.addEventListener(\"change\", function() {\n");
      out.write("            handleAutomaticBidChange(counter);\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function handleAutomaticBidChange(counter) {\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("        var SetAutomaticBidPriceLabel = document.getElementById('SetAutomaticBidPriceLabel' + counter);\n");
      out.write("        var SetAutomaticBidPrice = document.getElementById('SetAutomaticBidPrice' + counter);\n");
      out.write("        var SetAutomaticBidIncrementPriceLabel = document.getElementById('SetAutomaticBidIncrementPriceLabel' + counter);\n");
      out.write("        var SetAutomaticBidIncrementPrice = document.getElementById('SetAutomaticBidIncrementPrice' + counter);\n");
      out.write("\n");
      out.write("        const value = SetAutomaticBid.value;\n");
      out.write("\n");
      out.write("        if (value === 'true') {\n");
      out.write("            SetAutomaticBidPriceLabel.style.display = 'block';\n");
      out.write("            SetAutomaticBidPrice.style.display = 'block';\n");
      out.write("            SetAutomaticBidIncrementPriceLabel.style.display = 'block';\n");
      out.write("            SetAutomaticBidIncrementPrice.style.display = 'block';\n");
      out.write("        } else {\n");
      out.write("            SetAutomaticBidPriceLabel.style.display = 'none';\n");
      out.write("            SetAutomaticBidPrice.style.display = 'none';\n");
      out.write("            SetAutomaticBidIncrementPriceLabel.style.display = 'none';\n");
      out.write("            SetAutomaticBidIncrementPrice.style.display = 'none';\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function removeBid(counter) {\n");
      out.write("        var SetNewBidLabel = document.getElementById('SetNewBidLabel' + counter);\n");
      out.write("        var SetNewBid = document.getElementById('SetNewBid' + counter);\n");
      out.write("        var SetAutomaticBidLabel = document.getElementById('SetAutomaticBidLabel' + counter);\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("        var SetAutomaticBidPriceLabel = document.getElementById('SetAutomaticBidPriceLabel' + counter);\n");
      out.write("        var SetAutomaticBidPrice = document.getElementById('SetAutomaticBidPrice' + counter);\n");
      out.write("        var SetAutomaticBidIncrementPriceLabel = document.getElementById('SetAutomaticBidIncrementPriceLabel' + counter);\n");
      out.write("        var SetAutomaticBidIncrementPrice = document.getElementById('SetAutomaticBidIncrementPrice' + counter);\n");
      out.write("        var cancel = document.getElementById('cancel' + counter);\n");
      out.write("        var PlaceBid = document.getElementById('TopPlaceBid' + counter);\n");
      out.write("\n");
      out.write("        SetNewBidLabel.style.display = 'none';\n");
      out.write("        SetNewBid.style.display = 'none';\n");
      out.write("        SetAutomaticBidLabel.style.display = 'none';\n");
      out.write("        SetAutomaticBid.style.display = 'none';\n");
      out.write("        SetAutomaticBidPriceLabel.style.display = 'none';\n");
      out.write("        SetAutomaticBidPrice.style.display = 'none';\n");
      out.write("        SetAutomaticBidIncrementPriceLabel.style.display = 'none';\n");
      out.write("        SetAutomaticBidIncrementPrice.style.display = 'none';\n");
      out.write("        cancel.style.display = 'none';\n");
      out.write("        PlaceBid.style.display = 'none';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function placeBid(counter) {\n");
      out.write("        // handled by bidPage.jsp on submit\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");

    Integer userIdValue = (Integer) session.getAttribute("userIdValue");

    if (userIdValue == null) {
        out.println("<p style='color:red;'>User id not in session. Please log in again.</p>");
    } else {

        try {
            int counterValue = 0;

            // all items this user has ever bid on (by item type and item id)
            String sqlItems =
                    "select distinct itemTypeValue, itemIdValue " +
                            "from incrementbids " +
                            "where buyerIdValue = ? " +
                            "order by itemTypeValue, itemIdValue desc";

            PreparedStatement psItems = con.prepareStatement(sqlItems);
            psItems.setInt(1, userIdValue);
            ResultSet rsItems = psItems.executeQuery();

            List<String> itemTypes = new ArrayList<String>();
            List<Integer> itemIds = new ArrayList<Integer>();

            while (rsItems.next()) {
                itemTypes.add(rsItems.getString("itemTypeValue"));
                itemIds.add(rsItems.getInt("itemIdValue"));
            }
            rsItems.close();
            psItems.close();

            if (itemIds.isEmpty()) {
                out.println("<p>You have no bid notifications yet.</p>");
            }

            for (int i = 0; i < itemIds.size(); i++) {

                String itemTypeVal = itemTypes.get(i);   // "tops", "bottoms", "shoes"
                int itemIdVal = itemIds.get(i);

                // get the column name for that table
                String tableName;
                String idColumn;

                if ("tops".equals(itemTypeVal)) {
                    tableName = "tops";
                    idColumn  = "topIdValue";
                } else if ("bottoms".equals(itemTypeVal)) {
                    tableName = "bottoms";
                    idColumn  = "bottomIdValue";
                } else if ("shoes".equals(itemTypeVal)) {
                    tableName = "shoes";
                    idColumn  = "shoeIdValue";
                } else {
                    continue;  // skip unknown type
                }

                // user last bid for this item
                String sqlUserBid =
                        "select newBidValue " +
                                "from incrementbids " +
                                "where buyerIdValue = ? and itemTypeValue = ? and itemIdValue = ? " +
                                "order by bidIdValue desc limit 1";
                PreparedStatement psUserBid = con.prepareStatement(sqlUserBid);
                psUserBid.setInt(1, userIdValue);
                psUserBid.setString(2, itemTypeVal);
                psUserBid.setInt(3, itemIdVal);
                ResultSet rsUserBid = psUserBid.executeQuery();

                Float userBid = null;
                if (rsUserBid.next()) {
                    userBid = rsUserBid.getFloat("newBidValue");
                }
                rsUserBid.close();
                psUserBid.close();

                // current highest bid for this item
                String sqlCurrentBid =
                        "select newBidValue " +
                                "from incrementbids " +
                                "where itemTypeValue = ? and itemIdValue = ? " +
                                "order by bidIdValue desc limit 1";
                PreparedStatement psCurrentBid = con.prepareStatement(sqlCurrentBid);
                psCurrentBid.setString(1, itemTypeVal);
                psCurrentBid.setInt(2, itemIdVal);
                ResultSet rsCurrentBid = psCurrentBid.executeQuery();

                Float currentBid = null;
                if (rsCurrentBid.next()) {
                    currentBid = rsCurrentBid.getFloat("newBidValue");
                }
                rsCurrentBid.close();
                psCurrentBid.close();

                // get item information from the correct table
                String sqlItemInfo =
                        "select i.*, u.usernameValue as sellerUsername " +
                                "from " + tableName + " i " +
                                "join users u on i.auctionSellerIdValue = u.userIdValue " +
                                "where i." + idColumn + " = ?";
                PreparedStatement psItemInfo = con.prepareStatement(sqlItemInfo);
                psItemInfo.setInt(1, itemIdVal);
                ResultSet rsItemInfo = psItemInfo.executeQuery();

                if (!rsItemInfo.next()) {
                    rsItemInfo.close();
                    psItemInfo.close();
                    continue;
                }

                String sellerUsername = rsItemInfo.getString("sellerUsername");
                String genderValueDisplay = rsItemInfo.getString("genderValue");
                String sizeValueDisplay = rsItemInfo.getString("sizeValue");
                String colorValueDisplay = rsItemInfo.getString("colorValue");
                String descriptionValueDisplay = rsItemInfo.getString("descriptionValue");
                String conditionValueDisplay = rsItemInfo.getString("conditionValue");
                float minimumBidPriceValueDisplay = rsItemInfo.getFloat("minimumBidPriceValue");
                float startingOrCurrentBidPriceValueDisplay = rsItemInfo.getFloat("startingOrCurrentBidPriceValue");
                String auctionCloseDateValueDisplay = rsItemInfo.getString("auctionCloseDateValue");
                String auctionCloseTimeValueDisplay = rsItemInfo.getString("auctionCloseTimeValue");

                rsItemInfo.close();
                psItemInfo.close();

                out.println("<div style='border:1px solid #ccc; margin:10px; padding:10px;'>");
                out.println("<p><strong>Item Type:</strong> " + itemTypeVal + "</p>");
                out.println("<p><strong>Item ID:</strong> " + itemIdVal + "</p>");
                out.println("<p><strong>Seller:</strong> " + sellerUsername + "</p>");
                out.println("<p><strong>Gender:</strong> " + genderValueDisplay + "</p>");
                out.println("<p><strong>Size:</strong> " + sizeValueDisplay + "</p>");
                out.println("<p><strong>Color:</strong> " + colorValueDisplay + "</p>");
                out.println("<p><strong>Description:</strong> " + descriptionValueDisplay + "</p>");
                out.println("<p><strong>Condition:</strong> " + conditionValueDisplay + "</p>");

                if (minimumBidPriceValueDisplay != 0.0f) {
                    out.println("<p><strong>Minimum Bid Price:</strong> " + minimumBidPriceValueDisplay + "</p>");
                } else {
                    out.println("<p><strong>Minimum Bid Price:</strong> None</p>");
                }

                out.println("<p><strong>Current price on item field:</strong> "
                        + startingOrCurrentBidPriceValueDisplay + "</p>");
                out.println("<p><strong>Auction Close Date:</strong> " + auctionCloseDateValueDisplay + "</p>");
                out.println("<p><strong>Auction Close Time:</strong> " + auctionCloseTimeValueDisplay + "</p>");

                if (userBid != null && currentBid != null) {
                    out.println("<p><strong>Your last bid:</strong> " + userBid + "</p>");
                    out.println("<p><strong>Current highest bid:</strong> " + currentBid + "</p>");

                    if (userBid < currentBid) {
                        out.println("<p style='color:red;'>You have been outbid.</p>");
                    } else if (userBid.equals(currentBid)) {
                        out.println("<p style='color:green;'>You are currently the highest bidder.</p>");
                    }
                } else {
                    out.println("<p>No bid information found for this item.</p>");
                }

                // view bid history button (uses itemType + itemIdValue)
                out.println("<form method='get' action='bidHistory.jsp' style='margin-top:10px;'>");
                out.println("<input type='hidden' name='itemType' value='" + itemTypeVal + "'/>");
                out.println("<input type='hidden' name='itemIdValue' value='" + itemIdVal + "'/>");
                out.println("<input type='submit' value='View Bid History'/>");
                out.println("</form>");

                // show bid form only when user is outbid
                if (userBid != null && currentBid != null && userBid < currentBid) {

                    int localCounter = counterValue++;

                    out.println("<hr/>");
                    out.println("<input type='button' value='Create New Bid' " +
                            "onclick='createBid(" + localCounter + ")' " +
                            "id='TopCreateBid" + localCounter + "' style='margin-bottom: 20px;'>");

                    out.println("<form method='post' action='bidPage.jsp'>");
                    out.println("<input type='hidden' name='itemType' value='" + itemTypeVal + "'>");
                    out.println("<input type='hidden' name='itemIdValue' value='" + itemIdVal + "'>");

                    out.println("<label for='setNewBid' id='SetNewBidLabel" + localCounter + "' style='display: none;'>Set Bid (USD): </label>");
                    out.println("<input type='number' name='setNewBid' id='SetNewBid" + localCounter + "' style='display: none;' required>");

                    out.println("<label for='setAutomaticBid' id='SetAutomaticBidLabel" + localCounter + "' style='display: none;'>Set Automatic Bid: </label>");
                    out.println("<select name='setAutomaticBid' id='SetAutomaticBid" + localCounter + "' style='display: none;' required>");
                    out.println("<option value='selectAnItem' disabled selected>Select Item...</option>");
                    out.println("<option value='true'>Yes</option>");
                    out.println("<option value='false'>No</option>");
                    out.println("</select>");

                    out.println("<label for='maxBidPrice' id='SetAutomaticBidPriceLabel" + localCounter + "' style='display: none;'>Set Max Bid Price (USD): </label>");
                    out.println("<input type='number' name='maxBidPrice' id='SetAutomaticBidPrice" + localCounter + "' style='display: none;'>");

                    out.println("<label for='SetAutomaticBidIncrementPrice' id='SetAutomaticBidIncrementPriceLabel" + localCounter + "' style='display: none;'>Bid Increment Price (USD): </label>");
                    out.println("<input type='number' name='SetAutomaticBidIncrementPrice' id='SetAutomaticBidIncrementPrice" + localCounter + "' style='display: none;'>");

                    out.println("<input type='button' value='Cancel Bid' onclick='removeBid(" + localCounter + ")' id='cancel" + localCounter + "' style='display: none;'>");
                    out.println("<input type='submit' value='Place Bid' onclick='placeBid(" + localCounter + ")' id='TopPlaceBid" + localCounter + "' style='display: none;'>");
                    out.println("</form>");
                }

                out.println("</div>");
            }
        } catch (Exception e) {
            out.println("<p style='color:red;'>Error loading notifications: " + e.getMessage() + "</p>");
            e.printStackTrace();
        }
    }

    con.close();

      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
