/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-07 10:44:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import java.sql.*;

public final class notifications_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
response.setHeader("Pragma", "no-cache");
response.setDateHeader("Expires", 0);

Class.forName("com.mysql.jdbc.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/thriftShop","root", "Xcrafty!3my");
con.setAutoCommit(true);
con.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
Statement st = con.createStatement();

      out.write("\n");
      out.write("<script>\n");
      out.write("function createBid(counter) {\n");
      out.write("    var SetNewBidLabel = document.getElementById('SetNewBidLabel' + counter);\n");
      out.write("    var SetNewBid = document.getElementById('SetNewBid' + counter);\n");
      out.write("    var SetAutomaticBidLabel = document.getElementById('SetAutomaticBidLabel' + counter);\n");
      out.write("    var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("    var cancel = document.getElementById('cancel' + counter);\n");
      out.write("    var PlaceBid = document.getElementById('TopPlaceBid' + counter);\n");
      out.write("    \n");
      out.write("    SetNewBidLabel.style.display = 'block';\n");
      out.write("    SetNewBid.style.display = 'block';\n");
      out.write("    SetAutomaticBidLabel.style.display = 'block';\n");
      out.write("    SetAutomaticBid.style.display = 'block';\n");
      out.write("    cancel.style.display = 'block';\n");
      out.write("    PlaceBid.style.display = 'block';\n");
      out.write("    \n");
      out.write("    SetAutomaticBid.addEventListener(\"change\", function() {\n");
      out.write("        handleAutomaticBidChange(counter);\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function handleAutomaticBidChange(counter) {\n");
      out.write("    var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("    var SetAutomaticBidPriceLabel = document.getElementById('SetAutomaticBidPriceLabel' + counter);\n");
      out.write("    var SetAutomaticBidPrice = document.getElementById('SetAutomaticBidPrice' + counter);\n");
      out.write("    var SetAutomaticBidIncrementPriceLabel = document.getElementById('SetAutomaticBidIncrementPriceLabel' + counter);\n");
      out.write("    var SetAutomaticBidIncrementPrice = document.getElementById('SetAutomaticBidIncrementPrice' + counter);\n");
      out.write("    \n");
      out.write("    const value = SetAutomaticBid.value;\n");
      out.write("    \n");
      out.write("    if(value === 'true') {\n");
      out.write("        SetAutomaticBidPriceLabel.style.display = 'block';\n");
      out.write("        SetAutomaticBidPrice.style.display = 'block';\n");
      out.write("        SetAutomaticBidIncrementPriceLabel.style.display = 'block';\n");
      out.write("        SetAutomaticBidIncrementPrice.style.display = 'block';\n");
      out.write("    } else {\n");
      out.write("        SetAutomaticBidPriceLabel.style.display = 'none';\n");
      out.write("        SetAutomaticBidPrice.style.display = 'none';\n");
      out.write("        SetAutomaticBidIncrementPriceLabel.style.display = 'none';\n");
      out.write("        SetAutomaticBidIncrementPrice.style.display = 'none';\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function removeBid(counter) {\n");
      out.write("    var SetNewBidLabel = document.getElementById('SetNewBidLabel' + counter);\n");
      out.write("    var SetNewBid = document.getElementById('SetNewBid' + counter);\n");
      out.write("    var SetAutomaticBidLabel = document.getElementById('SetAutomaticBidLabel' + counter);\n");
      out.write("    var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("    var SetAutomaticBidPriceLabel = document.getElementById('SetAutomaticBidPriceLabel' + counter);\n");
      out.write("    var SetAutomaticBidPrice = document.getElementById('SetAutomaticBidPrice' + counter);\n");
      out.write("    var SetAutomaticBidIncrementPriceLabel = document.getElementById('SetAutomaticBidIncrementPriceLabel' + counter);\n");
      out.write("    var SetAutomaticBidIncrementPrice = document.getElementById('SetAutomaticBidIncrementPrice' + counter);\n");
      out.write("    var cancel = document.getElementById('cancel' + counter);\n");
      out.write("    var PlaceBid = document.getElementById('TopPlaceBid' + counter);\n");
      out.write("    \n");
      out.write("    SetNewBidLabel.style.display = 'none';\n");
      out.write("    SetNewBid.style.display = 'none';\n");
      out.write("    SetAutomaticBidLabel.style.display = 'none';\n");
      out.write("    SetAutomaticBid.style.display = 'none';\n");
      out.write("    SetAutomaticBidPriceLabel.style.display = 'none';\n");
      out.write("    SetAutomaticBidPrice.style.display = 'none';\n");
      out.write("    SetAutomaticBidIncrementPriceLabel.style.display = 'none';\n");
      out.write("    SetAutomaticBidIncrementPrice.style.display = 'none';\n");
      out.write("    cancel.style.display = 'none';\n");
      out.write("    PlaceBid.style.display = 'none';\n");
      out.write("}\n");
      out.write("\n");
      out.write("function placeBid(counter) {\n");
      out.write("    \n");
      out.write("}\n");
      out.write("</script>\n");


String counter = "select bidIdValue from topsIncrementBids order by bidIdValue desc LIMIT 1";
ResultSet counterResult = st.executeQuery(counter);
Integer counterValue = 0;
while(counterResult.next()) {
    counterValue = counterResult.getInt("bidIdValue");
}

Integer userIdValue = (Integer) session.getAttribute("userIdValue");
String bidNotifications = "select distinct topIdValue from topsIncrementBids where buyerIdValue = '" + userIdValue + "' order by topIdValue desc";
ResultSet bidNotificationsResult = st.executeQuery(bidNotifications);

List<Integer> topIdValueOfItemsBiddedOnByBidder = new ArrayList<>();
while(bidNotificationsResult.next()) {
    Integer topIdValue = bidNotificationsResult.getInt("topIdValue");  
    topIdValueOfItemsBiddedOnByBidder.add(topIdValue);
}

for(int i = 0; i < topIdValueOfItemsBiddedOnByBidder.size(); i++) {
    String buyersBidPrice = "select newBidValue from topsIncrementBids where buyerIdValue = '" + userIdValue + "' and topIdValue = '" + topIdValueOfItemsBiddedOnByBidder.get(i) + "' order by bidIdValue desc LIMIT 1";
    ResultSet buyersBidPriceResult = st.executeQuery(buyersBidPrice);
    
    Integer buyersBidPriceValue = null;
    if(buyersBidPriceResult.next()) {  
        buyersBidPriceValue = buyersBidPriceResult.getInt("newBidValue"); 
    }
    buyersBidPriceResult.close();

    String currentBidPrice = "select newBidValue from topsIncrementBids where topIdValue = '" + topIdValueOfItemsBiddedOnByBidder.get(i) + "' order by bidIdValue desc LIMIT 1";
    ResultSet currentBidPriceResult = st.executeQuery(currentBidPrice);
    
    Integer currentBidPriceValue = null;
    if(currentBidPriceResult.next()) { 
        currentBidPriceValue = currentBidPriceResult.getInt("newBidValue"); 
    }

    if(buyersBidPriceValue != null && currentBidPriceValue != null && buyersBidPriceValue < currentBidPriceValue) {

        // CHECK IF USER HAS AUTOMATIC BID SET UP
        String biddersMaxBidValue = "select bidMaxValue, bidIncrementValue from topsIncrementBids where buyerIdValue = '" + userIdValue + "' and topIdValue = '" + topIdValueOfItemsBiddedOnByBidder.get(i) + "' order by bidIdValue desc LIMIT 1";
        ResultSet biddersMaxBidValueResult = st.executeQuery(biddersMaxBidValue);
        Integer biddersMaxBidValueValue = null;
        Integer usersBidIncrementValue = null;
        
        if(biddersMaxBidValueResult.next()) {  
            biddersMaxBidValueValue = biddersMaxBidValueResult.getInt("bidMaxValue");
            usersBidIncrementValue = biddersMaxBidValueResult.getInt("bidIncrementValue");
        }
        
        if(biddersMaxBidValueValue != null && usersBidIncrementValue != null && 
           biddersMaxBidValueValue != 0 && usersBidIncrementValue != 0 &&
           (currentBidPriceValue + usersBidIncrementValue) <= biddersMaxBidValueValue) {
            
            Integer newBidValueWithIncrementedPrice = currentBidPriceValue + usersBidIncrementValue;
            counterValue++; 
            
            String updateCurrentBidPriceInTopsTable = "update tops set startingOrCurrentBidPriceValue = '" + newBidValueWithIncrementedPrice + "' where topIdValue = '" + topIdValueOfItemsBiddedOnByBidder.get(i) + "'";
            st.executeUpdate(updateCurrentBidPriceInTopsTable);
            
            String insertnewBidValueWithIncrementedPriceinTopsIncrementBids = "insert into topsIncrementBids (bidIdValue, topIdValue, buyerIdValue, newBidValue, bidIncrementValue, bidMaxValue) values ('" + counterValue + "', '" + topIdValueOfItemsBiddedOnByBidder.get(i) + "','" + userIdValue + "' ,'" + newBidValueWithIncrementedPrice + "' ,'" + usersBidIncrementValue + "', '" + biddersMaxBidValueValue + "')";
            st.executeUpdate(insertnewBidValueWithIncrementedPriceinTopsIncrementBids);
            
            // UPDATE currentBidPriceValue FOR DISPLAY
            currentBidPriceValue = newBidValueWithIncrementedPrice;
            buyersBidPriceValue = newBidValueWithIncrementedPrice;
        }

        String topInformation = "select * from tops where topIdValue = '" + topIdValueOfItemsBiddedOnByBidder.get(i) + "'";  
        ResultSet topInformationResult = st.executeQuery(topInformation);
        Integer topInformationValue = topIdValueOfItemsBiddedOnByBidder.get(i);

        if(topInformationResult.next()) {  
            
            String genderValueDisplay = topInformationResult.getString("genderValue");
            String sizeValueDisplay = topInformationResult.getString("sizeValue");
            String colorValueDisplay = topInformationResult.getString("colorValue");
            String frontLengthValueDisplay = topInformationResult.getString("frontLengthValue");
            String sleeveLengthValueDisplay = topInformationResult.getString("sleeveLengthValue");
            String descriptionValueDisplay = topInformationResult.getString("descriptionValue");
            String conditionValueDisplay = topInformationResult.getString("conditionValue");
            Float minimumBidPriceValueDisplay = topInformationResult.getFloat("minimumBidPriceValue");
            Float startingOrCurrentBidPriceValueDisplay = topInformationResult.getFloat("startingOrCurrentBidPriceValue");
            String auctionCloseDateValueDisplay = topInformationResult.getString("auctionCloseDateValue");
            String auctionCloseTimeValueDisplay = topInformationResult.getString("auctionCloseTimeValue");

            out.println("<div>");
            out.println("<p>Gender: " + genderValueDisplay + "</p>");
            out.println("<p>Size: " + sizeValueDisplay + "</p>");
            out.println("<p>Color: " + colorValueDisplay + "</p>");
            out.println("<p>Front Length: " + frontLengthValueDisplay + "</p>");
            out.println("<p>Sleeve Length: " + sleeveLengthValueDisplay + "</p>");
            out.println("<p>Description: " + descriptionValueDisplay + "</p>");
            out.println("<p>Condition: " + conditionValueDisplay + "</p>");
            if(minimumBidPriceValueDisplay != null && minimumBidPriceValueDisplay != 0.0f) {  
                out.println("<p>Minimum Bid Price: " + minimumBidPriceValueDisplay + "</p>");
            }
            else {
                out.println("<p>Minimum Bid Price: None</p>");
            }    
            out.println("<p>Starting or Current Bid Price: " + startingOrCurrentBidPriceValueDisplay + "</p>");
            out.println("<p>Auction Close Date: " + auctionCloseDateValueDisplay + "</p>");
            out.println("<p>Auction Close Time: " + auctionCloseTimeValueDisplay + "</p>");
            
            // CHECK AGAIN IF MAX BID EXCEEDED (for display message)
            if(biddersMaxBidValueValue != null && currentBidPriceValue != null && 
               biddersMaxBidValueValue != 0 && currentBidPriceValue > biddersMaxBidValueValue) {
                out.println("<p>The bid price for the following top has gone to " + currentBidPriceValue + ", which exceeds your Maximum Bid Price of " + biddersMaxBidValueValue + ". If you want to change this please create a new bid!</p>");
            }
            else{
                out.println("<p>The bid price for the following top has gone to " + currentBidPriceValue + ". You have been outbid.</p>");
            }
            
            out.println("<input type='submit' value='Create New Bid' onclick='createBid(" + counterValue + ")' id='TopCreateBid" + counterValue + "' style='margin-bottom: 100px;'>");
            out.println("<form method='post' action='bidPage.jsp'>");
            out.println("<input type='hidden' name='topIdValue' value='" + topInformationValue +"'>");
            out.println("<label for='setNewBid' id='SetNewBidLabel" + counterValue + "' style='display: none;'>Set Bid (USD): </label>");
            out.println("<input type='number' name='setNewBid' id='SetNewBid" + counterValue + "' style='display: none;' required>");
            out.println("<label for='setAutomaticBid' id='SetAutomaticBidLabel" + counterValue + "' style='display: none;'>Set Automatic Bid : </label>");
            out.println("<select name='setAutomaticBid' id='SetAutomaticBid" + counterValue + "' style='display: none;' required>");
            out.println("<option value='selectAnItem' disabled selected>Select Item...</option>");
            out.println("<option value='true' id='true'>Yes</option>");
            out.println("<option value='false' id='false'>No</option>");
            out.println("</select>");
            out.println("<label for='maxBidPrice' id='SetAutomaticBidPriceLabel" + counterValue + "' style='display: none;'>Set Max Bid Price (USD): </label>");
            out.println("<input type='number' name='maxBidPrice' id='SetAutomaticBidPrice" + counterValue + "' style='display: none;'>");
            out.println("<label for='SetAutomaticBidIncrementPrice' id='SetAutomaticBidIncrementPriceLabel" + counterValue + "' style='display: none;'>Bid Increment Price (USD): </label>");
            out.println("<input type='number' name='SetAutomaticBidIncrementPrice' id='SetAutomaticBidIncrementPrice" + counterValue + "' style='display: none;'>");
            out.println("<input type='button' value='Cancel Bid' onclick='removeBid(" + counterValue + ")' id='cancel" + counterValue + "' style='display: none;'>");
            out.println("<input type='submit' value='Place Bid' onclick='placeBid(" + counterValue +")' id='TopPlaceBid" + counterValue + "' style='display: none;'>");
            out.println("</form>");
            out.println("</div>");
            counterValue++;
        }
    }
    else if (buyersBidPriceValue != null && currentBidPriceValue != null && buyersBidPriceValue.equals(currentBidPriceValue)) {
        String topInformation = "select * from tops where topIdValue = '" + topIdValueOfItemsBiddedOnByBidder.get(i) + "'";  
        ResultSet topInformationResult = st.executeQuery(topInformation);

        if(topInformationResult.next()) {  
            
            String genderValueDisplay = topInformationResult.getString("genderValue");
            String sizeValueDisplay = topInformationResult.getString("sizeValue");
            String colorValueDisplay = topInformationResult.getString("colorValue");
            String frontLengthValueDisplay = topInformationResult.getString("frontLengthValue");
            String sleeveLengthValueDisplay = topInformationResult.getString("sleeveLengthValue");
            String descriptionValueDisplay = topInformationResult.getString("descriptionValue");
            String conditionValueDisplay = topInformationResult.getString("conditionValue");
            Float minimumBidPriceValueDisplay = topInformationResult.getFloat("minimumBidPriceValue");
            Float startingOrCurrentBidPriceValueDisplay = topInformationResult.getFloat("startingOrCurrentBidPriceValue");
            String auctionCloseDateValueDisplay = topInformationResult.getString("auctionCloseDateValue");
            String auctionCloseTimeValueDisplay = topInformationResult.getString("auctionCloseTimeValue");

            out.println("<div>");
            out.println("<p>Gender: " + genderValueDisplay + "</p>");
            out.println("<p>Size: " + sizeValueDisplay + "</p>");
            out.println("<p>Color: " + colorValueDisplay + "</p>");
            out.println("<p>Front Length: " + frontLengthValueDisplay + "</p>");
            out.println("<p>Sleeve Length: " + sleeveLengthValueDisplay + "</p>");
            out.println("<p>Description: " + descriptionValueDisplay + "</p>");
            out.println("<p>Condition: " + conditionValueDisplay + "</p>");
            if(minimumBidPriceValueDisplay != null && minimumBidPriceValueDisplay != 0.0f) {  
                out.println("<p>Minimum Bid Price: " + minimumBidPriceValueDisplay + "</p>");
            }
            else {
                out.println("<p>Minimum Bid Price: None</p>");
            }    
            out.println("<p>Starting or Current Bid Price: " + startingOrCurrentBidPriceValueDisplay + "</p>");
            out.println("<p>Auction Close Date: " + auctionCloseDateValueDisplay + "</p>");
            out.println("<p>Auction Close Time: " + auctionCloseTimeValueDisplay + "</p>");
            out.println("<p>You are currently the highest bidder you are winning!</p>");
            out.println("</div>");
        }
    }
}


st.close();
con.close();    

    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
