/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-06 03:32:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
 if (session.getAttribute("username")==null) { response.sendRedirect("../LoginPage/login.jsp"); return; } 
      out.write("\r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("        <html>\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <title>Profile Page</title>\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("            <script>\r\n");
      out.write("\r\n");
      out.write("                document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("\r\n");
      out.write("                    document.getElementById('itemsTypeSelect').addEventListener(\"change\", function () {\r\n");
      out.write("                        const value = this.value;\r\n");
      out.write("\r\n");
      out.write("                        if (value === \"tops\") {\r\n");
      out.write("                            document.getElementById('auctionFillOutFormTops').style.display = \"block\";\r\n");
      out.write("                            document.getElementById('auctionFillOutFormBottoms').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('auctionFillOutFormShoes').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('TopSubmit').style.display = \"block\";\r\n");
      out.write("                            document.getElementById('BottomSubmit').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('ShoeSubmit').style.display = \"none\";\r\n");
      out.write("                        }\r\n");
      out.write("                        if (value === \"bottoms\") {\r\n");
      out.write("                            document.getElementById('auctionFillOutFormBottoms').style.display = \"block\";\r\n");
      out.write("                            document.getElementById('auctionFillOutFormTops').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('auctionFillOutFormShoes').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('BottomSubmit').style.display = \"block\";\r\n");
      out.write("                            document.getElementById('TopSubmit').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('ShoeSubmit').style.display = \"none\";\r\n");
      out.write("                        }\r\n");
      out.write("                        if (value === \"shoes\") {\r\n");
      out.write("                            document.getElementById('auctionFillOutFormShoes').style.display = \"block\";\r\n");
      out.write("                            document.getElementById('auctionFillOutFormTops').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('auctionFillOutFormBottoms').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('ShoeSubmit').style.display = \"block\";\r\n");
      out.write("                            document.getElementById('TopSubmit').style.display = \"none\";\r\n");
      out.write("                            document.getElementById('BottomSubmit').style.display = \"none\";\r\n");
      out.write("                        }\r\n");
      out.write("                    })\r\n");
      out.write("                })\r\n");
      out.write("\r\n");
      out.write("                function createAuction() {\r\n");
      out.write("                    document.getElementById('auctionFillOutForm').style.display = \"block\";\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            </script>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <span>User: ");
      out.print( session.getAttribute("username") );
      out.write("</span>\r\n");
      out.write("                <a href='mainPage.jsp'>Main Page</a>\r\n");
      out.write("                <a href='../LoginPage/logout.jsp'>Log Out</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"auctionFillOutForm\" style=\"display: none;\">\r\n");
      out.write("                <label for=\"itemsType\">Choose Item Type: </label>\r\n");
      out.write("                <select name=\"itemsType\" id=\"itemsTypeSelect\" required>\r\n");
      out.write("                    <option value=\"selectAnItem\" disabled selected>Select Item...</option>\r\n");
      out.write("                    <option value=\"tops\" id=\"tops\">Tops</option>\r\n");
      out.write("                    <option value=\"bottoms\" id=\"bottoms\">Bottoms</option>\r\n");
      out.write("                    <option value=\"shoes\" id=\"shoes\">Shoes</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"tops.jsp\" method=\"POST\">\r\n");
      out.write("                <div id=\"auctionFillOutFormTops\" style=\"display: none;\">\r\n");
      out.write("                    <label for=\"topGender\">Gender: </label>\r\n");
      out.write("                    <select name=\"topGender\" id=\"topsGenderLabel\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Gender...</option>\r\n");
      out.write("                        <option value=\"Male\">Male</option>\r\n");
      out.write("                        <option value=\"Female\">Female</option>\r\n");
      out.write("                        <option value=\"Unisex\">Unisex</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"topSize\">Top Size:</label>\r\n");
      out.write("                    <select name=\"topSize\" id=\"topSizeSelect\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Size...</option>\r\n");
      out.write("                        <option value=\"XS\">XS</option>\r\n");
      out.write("                        <option value=\"S\">S</option>\r\n");
      out.write("                        <option value=\"M\">M</option>\r\n");
      out.write("                        <option value=\"L\">L</option>\r\n");
      out.write("                        <option value=\"XL\">XL</option>\r\n");
      out.write("                        <option value=\"XXL\">XXL</option>\r\n");
      out.write("                        <option value=\"3XL\">3XL</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"topColor\">Color: </label>\r\n");
      out.write("                    <select name=\"topColor\" id=\"TopColorColor\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Color...</option>\r\n");
      out.write("                        <option value=\"Black\">Black</option>\r\n");
      out.write("                        <option value=\"Blue\">Blue</option>\r\n");
      out.write("                        <option value=\"Gray\">Gray</option>\r\n");
      out.write("                        <option value=\"White\">White</option>\r\n");
      out.write("                        <option value=\"Brown\">Brown</option>\r\n");
      out.write("                        <option value=\"Red\">Red</option>\r\n");
      out.write("                        <option value=\"Pink\">Pink</option>\r\n");
      out.write("                        <option value=\"Orange\">Orange</option>\r\n");
      out.write("                        <option value=\"Yellow\">Yellow</option>\r\n");
      out.write("                        <option value=\"Green\">Green</option>\r\n");
      out.write("                        <option value=\"Purple\">Purple</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"FrontLength\">Front Length (cm): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"FrontLength\" id=\"FrontLengthTop\" required>\r\n");
      out.write("                    <label for=\"ChestLength\">Chest Length (cm): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"ChestLength\" id=\"ChestLengthTop\" required>\r\n");
      out.write("                    <label for=\"SleeveLength\">Sleeve Length (cm): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"SleeveLength\" id=\"SleeveLengthTop\" required>\r\n");
      out.write("                    <label for=\"Description\">Description: </label>\r\n");
      out.write("                    <input name=\"Description\" id=\"DescriptionTop\" maxLength=\"200\" required>\r\n");
      out.write("                    <label for=\"Condition\">Condition: </label>\r\n");
      out.write("                    <input name=\"Condition\" id=\"ConditionTop\" maxLength=\"200\" required>\r\n");
      out.write("                    <label for=\"Minimum\">Minimum Bid Price (USD): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"Minimum\" id=\"MinimumBidConditionTop\">\r\n");
      out.write("                    <label for=\"StartingOrCurrentBidPrice\">Starting Bid Price(USD): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"StartingOrCurrentBidPrice\" id=\"StartingOrCurrentBidPriceTop\"\r\n");
      out.write("                        required>\r\n");
      out.write("                    <label for=\"AuctionCloseDateTops\">Auction Close Date: </label>\r\n");
      out.write("                    <input type=\"date\" name=\"AuctionCloseDateTops\" id=\"AuctionCloseTopsDate\" required>\r\n");
      out.write("                    <label for=\"AuctionCloseTime\">Auction Close Time: </label>\r\n");
      out.write("                    <input type=\"time\" name=\"AuctionCloseTimeTops\" id=\"AuctionCloseTopsTime\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"submit\" value=\"Submit\" id=\"TopSubmit\" style=\"display: none;\" />\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"bottoms.jsp\" method=\"POST\">\r\n");
      out.write("                <div id=\"auctionFillOutFormBottoms\" style=\"display: none;\">\r\n");
      out.write("                    <label for=\"bottomGender\">Gender: </label>\r\n");
      out.write("                    <select name=\"bottomGender\" id=\"bottomGenderSelect\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Gender...</option>\r\n");
      out.write("                        <option value=\"Male\">Male</option>\r\n");
      out.write("                        <option value=\"Female\">Female</option>\r\n");
      out.write("                        <option value=\"Unisex\">Unisex</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"bottomSize\">Bottom Size: </label>\r\n");
      out.write("                    <select name=\"bottomSize\" id=\"bottomSizeSelect\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Size...</option>\r\n");
      out.write("                        <option value=\"XS\">XS</option>\r\n");
      out.write("                        <option value=\"S\">S</option>\r\n");
      out.write("                        <option value=\"M\">M</option>\r\n");
      out.write("                        <option value=\"L\">L</option>\r\n");
      out.write("                        <option value=\"XL\">XL</option>\r\n");
      out.write("                        <option value=\"XXL\">XXL</option>\r\n");
      out.write("                        <option value=\"3XL\">3XL</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"bottomColor\">Color: </label>\r\n");
      out.write("                    <select name=\"bottomColor\" id=\"bottomColorColor\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Color...</option>\r\n");
      out.write("                        <option value=\"Black\">Black</option>\r\n");
      out.write("                        <option value=\"Blue\">Blue</option>\r\n");
      out.write("                        <option value=\"Gray\">Gray</option>\r\n");
      out.write("                        <option value=\"White\">White</option>\r\n");
      out.write("                        <option value=\"Brown\">Brown</option>\r\n");
      out.write("                        <option value=\"Red\">Red</option>\r\n");
      out.write("                        <option value=\"Pink\">Pink</option>\r\n");
      out.write("                        <option value=\"Orange\">Orange</option>\r\n");
      out.write("                        <option value=\"Yellow\">Yellow</option>\r\n");
      out.write("                        <option value=\"Green\">Green</option>\r\n");
      out.write("                        <option value=\"Purple\">Purple</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"WaistLength\">Waist Length (cm): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"WaistLength\" id=\"WaistLengthBottom\" required>\r\n");
      out.write("                    <label for=\"InseamLength\">Inseam Length (cm): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"InseamLength\" id=\"InseamLengthBottom\" required>\r\n");
      out.write("                    <label for=\"OutseamLength\">Outseam Length (cm): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"OutseamLength\" id=\"OutseamLengthBottom\" required>\r\n");
      out.write("                    <label for=\"HipLength\">Hip Length (cm): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"HipLength\" id=\"HipLengthBottom\" required>\r\n");
      out.write("                    <label for=\"RiseLength\">Rise Length (cm): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"RiseLength\" id=\"RiseLengthBottom\" required>\r\n");
      out.write("                    <label for=\"Description\">Description: </label>\r\n");
      out.write("                    <input name=\"Description\" id=\"DescriptionBottom\" required>\r\n");
      out.write("                    <label for=\"Condition\">Condition: </label>\r\n");
      out.write("                    <input name=\"Condition\" id=\"ConditionBottom\" required>\r\n");
      out.write("                    <label for=\"Minimum\">Minimum Bid Price (USD): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"Minimum\" id=\"MinimumBidConditionBottom\">\r\n");
      out.write("                    <label for=\"AuctionCloseDateBottoms\">Auction Close Date: </label>\r\n");
      out.write("                    <input type=\"date\" name=\"AuctionCloseDateBottoms\" id=\"AuctionCloseBottomsDate\">\r\n");
      out.write("                    <label for=\"AuctionCloseTimeBottoms\">Auction Close Time: </label>\r\n");
      out.write("                    <input type=\"time\" name=\"AuctionCloseTimeBottoms\" id=\"AuctionCloseBottomsTime\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"submit\" value=\"Submit\" id=\"BottomSubmit\" style=\"display: none;\" />\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"shoes.jsp\" method=\"POST\">\r\n");
      out.write("                <div id=\"auctionFillOutFormShoes\" style=\"display: none;\">\r\n");
      out.write("                    <label for=\"shoeGender\">Gender: </label>\r\n");
      out.write("                    <select name=\"shoeGender\" id=\"shoeGenderSelect\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Gender...</option>\r\n");
      out.write("                        <option value=\"Male\">Male</option>\r\n");
      out.write("                        <option value=\"Female\">Female</option>\r\n");
      out.write("                        <option value=\"Unisex\">Unisex</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"shoeSize\">Shoe Size: </label>\r\n");
      out.write("                    <select name=\"shoeSize\" id=\"shoeSizeSelect\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Size...</option>\r\n");
      out.write("                        <option value=\"1\">1</option>\r\n");
      out.write("                        <option value=\"2\">2</option>\r\n");
      out.write("                        <option value=\"3\">3</option>\r\n");
      out.write("                        <option value=\"4\">4</option>\r\n");
      out.write("                        <option value=\"5\">5</option>\r\n");
      out.write("                        <option value=\"6\">6</option>\r\n");
      out.write("                        <option value=\"7\">7</option>\r\n");
      out.write("                        <option value=\"8\">8</option>\r\n");
      out.write("                        <option value=\"9\">9</option>\r\n");
      out.write("                        <option value=\"10\">10</option>\r\n");
      out.write("                        <option value=\"11\">11</option>\r\n");
      out.write("                        <option value=\"12\">12</option>\r\n");
      out.write("                        <option value=\"13\">13</option>\r\n");
      out.write("                        <option value=\"14\">14</option>\r\n");
      out.write("                        <option value=\"15\">15</option>\r\n");
      out.write("                        <option value=\"16\">16</option>\r\n");
      out.write("                        <option value=\"17\">17</option>\r\n");
      out.write("                        <option value=\"18\">18</option>\r\n");
      out.write("                        <option value=\"19\">19</option>\r\n");
      out.write("                        <option value=\"20\">20</option>\r\n");
      out.write("                        <option value=\"21\">21</option>\r\n");
      out.write("                        <option value=\"22\">22</option>\r\n");
      out.write("                        <option value=\"23\">23</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"shoeColor\">Color: </label>\r\n");
      out.write("                    <select type=\"color\" name=\"shoeColor\" id=\"ShoeColorColor\" required>\r\n");
      out.write("                        <option value=\"SelectASize\" disabled selected>Select Color...</option>\r\n");
      out.write("                        <option value=\"Black\">Black</option>\r\n");
      out.write("                        <option value=\"Blue\">Blue</option>\r\n");
      out.write("                        <option value=\"Gray\">Gray</option>\r\n");
      out.write("                        <option value=\"White\">White</option>\r\n");
      out.write("                        <option value=\"Brown\">Brown</option>\r\n");
      out.write("                        <option value=\"Red\">Red</option>\r\n");
      out.write("                        <option value=\"Pink\">Pink</option>\r\n");
      out.write("                        <option value=\"Orange\">Orange</option>\r\n");
      out.write("                        <option value=\"Yellow\">Yellow</option>\r\n");
      out.write("                        <option value=\"Green\">Green</option>\r\n");
      out.write("                        <option value=\"Purple\">Purple</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label for=\"Description\">Description: </label>\r\n");
      out.write("                    <input maxlength=\"200\" name=\"Description\" id=\"DescriptionShoe\" required>\r\n");
      out.write("                    <label for=\"Condition\">Condition: </label>\r\n");
      out.write("                    <input maxlength=\"200\" name=\"Condition\" id=\"ConditionShoe\" required>\r\n");
      out.write("                    <label for=\"Minimum\">Minimum Bid Price (USD): </label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" name=\"Minimum\" id=\"MinimumBidConditionShoe\">\r\n");
      out.write("                    <label for=\"AuctionCloseDateShoes\">Auction Close Date: </label>\r\n");
      out.write("                    <input type=\"date\" name=\"AuctionCloseDateShoes\" id=\"AuctionCloseShoesDate\">\r\n");
      out.write("                    <label for=\"AuctionCloseTimeShoes\">Auction Close Time: </label>\r\n");
      out.write("                    <input type=\"time\" name=\"AuctionCloseTimeShoes\" id=\"AuctionCloseShoesDate\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"submit\" value=\"Submit\" id=\"ShoeSubmit\" style=\"display: none;\" />\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <button onclick='createAuction()'>create auction</button>\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
