/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-07 00:09:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.Part;
import java.io.*;
import java.sql.*;
import jakarta.servlet.annotation.MultipartConfig;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;

public final class shoes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("jakarta.servlet.http.Part");
    _jspx_imports_classes.add("jakarta.servlet.annotation.MultipartConfig");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.LocalTime");
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Shoes - ThriftShop Auction</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/auction-style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <div class=\"header-container\">\n");
      out.write("            <a href=\"mainPage.jsp\" class=\"logo\">🏛️ ThriftShop</a>\n");
      out.write("            <nav>\n");
      out.write("                <ul class=\"nav-menu\">\n");
      out.write("                    <li><a href=\"tops.jsp\">Tops</a></li>\n");
      out.write("                    <li><a href=\"bottoms.jsp\">Bottoms</a></li>\n");
      out.write("                    <li><a href=\"shoes.jsp\">Shoes</a></li>\n");
      out.write("                    <li><a href=\"sellers.jsp\">Sellers</a></li>\n");
      out.write("                    <li><a href=\"notifications.jsp\">Notifications</a></li>\n");
      out.write("                    <li><a href=\"profile.jsp\">Profile</a></li>\n");
      out.write("                    <li><a href=\"../LoginPage/logout.jsp\">Logout</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"user-info\">👤 ");
      out.print(session.getAttribute("username"));
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <div class=\"container\">\n");
      out.write("\n");

    // load MySQL driver
    Class.forName("com.mysql.cj.jdbc.Driver");
    String jdbcUrl = System.getenv("JDBC_URL");
    if (jdbcUrl == null || jdbcUrl.isEmpty()) {
        String dbHost = System.getenv("DB_HOST");
        String dbPort = System.getenv("DB_PORT");
        String dbName = System.getenv("DB_NAME");
        if (dbHost == null) dbHost = "localhost";
        if (dbPort == null) dbPort = "3306";
        if (dbName == null) dbName = "thriftShop";
        jdbcUrl = "jdbc:mysql://" + dbHost + ":" + dbPort + "/" + dbName;
    }
    String dbUser = System.getenv("DB_USER");
    if (dbUser == null) dbUser = "root";
    String dbPass = System.getenv("DB_PASS");
    if (dbPass == null) dbPass = "12345";
    Connection con = DriverManager.getConnection(jdbcUrl, dbUser, dbPass);
    Statement st = con.createStatement();

    // check login
    if (session.getAttribute("username") == null) {
        response.sendRedirect("../LoginPage/login.jsp");
        return;
    }

      out.write("\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>👟 Shoes</h1>\n");
      out.write("            <p>Browse and bid on premium shoes</p>\n");
      out.write("            <a href=\"mainPage.jsp\" class=\"btn btn-outline\" style=\"margin-top: 1rem;\">← Back to Main Page</a>\n");
      out.write("        </div>\n");


    // Get Show Similars parameters
    String similarId = request.getParameter("similarId");
    String similarSize = request.getParameter("similarSize");
    String similarGender = request.getParameter("similarGender");
    String similarMinPrice = request.getParameter("similarMinPrice");
    String similarMaxPrice = request.getParameter("similarMaxPrice");

    boolean showingSimilar = (similarSize != null && !similarSize.isEmpty() &&
            similarGender != null && !similarGender.isEmpty());

    if (showingSimilar) {
        out.println("<p><strong>Showing Similar Shoes:</strong> Gender \"" + similarGender + "\" | Size \"" + similarSize + "\" | Price: $" + similarMinPrice + " - $" + similarMaxPrice);
        out.println("&nbsp;&nbsp;<a href='shoes.jsp'>Clear Filter</a></p>");
        out.println("<hr/>");
    }

    // handle new shoe auction submit
    String gender = request.getParameter("shoeGender");
    if (gender != null) {

        // read date and time
        String dateStr = request.getParameter("AuctionCloseDateShoes");
        String timeStr = request.getParameter("AuctionCloseTimeShoes");

        if (dateStr == null || timeStr == null ||
                dateStr.isEmpty() || timeStr.isEmpty()) {

            out.println("<p style='color:red'>Error. Auction close date or time is missing.</p>");
            out.println("<a href='../WebsitePages/mainPage.jsp'>Go back to Main Page</a>");
            st.close();
            con.close();
            return;
        }

        LocalDate closeDate = LocalDate.parse(dateStr);   // yyyy-MM-dd
        LocalTime closeTime = LocalTime.parse(timeStr);   // HH:mm
        LocalDateTime closeDateTime = LocalDateTime.of(closeDate, closeTime);
        LocalDateTime now = LocalDateTime.now();

        if (closeDateTime.isBefore(now)) {
            out.println("<p style='color:red'>Auction close date and time cannot be in the past.</p>");
            out.println("<a href='../WebsitePages/mainPage.jsp'>Go back to Main Page</a>");
            st.close();
            con.close();
            return;
        }

        // date and time are ok, read rest of fields
        Integer userIdValue = (Integer) session.getAttribute("userIdValue");
        String size        = request.getParameter("shoeSize");
        String color       = request.getParameter("shoeColor");
        String description = request.getParameter("Description");
        String condition   = request.getParameter("Condition");
        String minimum     = request.getParameter("Minimum");
        String startingorcurrentbidprice = request.getParameter("StartingOrCurrentBidPrice");

        String auctionDate = dateStr;
        String auctionTime = timeStr;

        if (minimum == null || minimum.isEmpty()) {
            minimum = "0.0";
        }

        // your form for shoes does not have StartingOrCurrentBidPrice
        // so if it is missing or empty, use minimum as starting price
        if (startingorcurrentbidprice == null || startingorcurrentbidprice.isEmpty()) {
            startingorcurrentbidprice = minimum;
        }

        String insert =
                "INSERT INTO shoes " +
                        "(auctionSellerIdValue, genderValue, sizeValue, colorValue, " +
                        " descriptionValue, conditionValue, minimumBidPriceValue, " +
                        " startingOrCurrentBidPriceValue, auctionCloseDateValue, auctionCloseTimeValue) " +
                        "VALUES ('" + userIdValue + "', '" + gender + "', '" + size + "', '" + color + "', " +
                        "'" + description + "', '" + condition + "', '" + minimum + "', " +
                        "'" + startingorcurrentbidprice + "', '" + auctionDate + "', '" + auctionTime + "')";

        st.executeUpdate(insert);
    }

    // Build query - with or without similarity filter
    StringBuilder shoesQuery = new StringBuilder(
            "SELECT s.*, u.usernameValue AS sellerUsername " +
                    "FROM shoes s " +
                    "JOIN users u ON s.auctionSellerIdValue = u.userIdValue " +
                    "WHERE 1=1");

    if (showingSimilar) {
        // Filter by gender
        if (similarGender != null && !similarGender.isEmpty()) {
            String safeGender = similarGender.replace("'", "''");
            shoesQuery.append(" AND s.genderValue = '").append(safeGender).append("'");
        }
        // Filter by size
        if (similarSize != null && !similarSize.isEmpty()) {
            String safeSize = similarSize.replace("'", "''");
            shoesQuery.append(" AND s.sizeValue = '").append(safeSize).append("'");
        }
        // Filter by price range
        if (similarMinPrice != null && !similarMinPrice.isEmpty()) {
            shoesQuery.append(" AND s.minimumBidPriceValue >= ").append(similarMinPrice);
        }
        if (similarMaxPrice != null && !similarMaxPrice.isEmpty()) {
            shoesQuery.append(" AND s.minimumBidPriceValue <= ").append(similarMaxPrice);
        }
        // Exclude the original item
        if (similarId != null && !similarId.isEmpty()) {
            shoesQuery.append(" AND s.shoeIdValue != ").append(similarId);
        }
    }

    shoesQuery.append(" ORDER BY s.shoeIdValue DESC");

    ResultSet rs = st.executeQuery(shoesQuery.toString());
    boolean found = false;
    
    out.println("<div class='items-grid'>");

    // display shoes
    while (rs.next()) {
        found = true;

        String sellerUsername  = rs.getString("sellerUsername");
        String shoeIdVal       = rs.getString("shoeIdValue");
        String genderVal       = rs.getString("genderValue");
        String sizeVal         = rs.getString("sizeValue");
        String colorVal        = rs.getString("colorValue");
        String descVal         = rs.getString("descriptionValue");
        String condVal         = rs.getString("conditionValue");
        float minBid           = rs.getFloat("minimumBidPriceValue");
        float startOrCurrent   = rs.getFloat("startingOrCurrentBidPriceValue");
        String auctionDateVal  = rs.getString("auctionCloseDateValue");
        String auctionTimeVal  = rs.getString("auctionCloseTimeValue");

        // Calculate price range for Show Similars (±10%)
        double simMinPrice = Math.round(minBid * 0.9 * 100.0) / 100.0;
        double simMaxPrice = Math.round(minBid * 1.1 * 100.0) / 100.0;

        // Only show minimum bid price (reserve) to the seller who created the auction
        Integer currentUserId = (Integer) session.getAttribute("userIdValue");
        String sellerIdStr = rs.getString("auctionSellerIdValue");
        boolean isSeller = (currentUserId != null && sellerIdStr != null && 
                           currentUserId.toString().equals(sellerIdStr));

        out.println("<div class='item-card'>");
        out.println("<div class='item-image'>👟</div>");
        out.println("<div class='item-body'>");
        out.println("<div class='item-title'>" + (descVal != null && !descVal.isEmpty() ? descVal : "Shoe #" + shoeIdVal) + "</div>");
        out.println("<div class='item-meta'>");
        out.println("<span>👤 Seller: " + sellerUsername + "</span> | ");
        out.println("<span>" + genderVal + "</span> | ");
        out.println("<span>Size: " + sizeVal + "</span> | ");
        out.println("<span>Color: " + colorVal + "</span>");
        out.println("</div>");
        
        out.println("<p style='margin: 0.5rem 0;'><strong>📝 Description:</strong> " + descVal + "</p>");
        out.println("<p style='margin: 0.5rem 0;'><strong>✨ Condition:</strong> " + condVal + "</p>");
        
        if (isSeller) {
            if (minBid != 0.0f) {
                out.println("<div class='reserve-badge' style='display: inline-block; margin: 0.5rem 0;'>🔒 Reserve: $" + minBid + " (Hidden)</div>");
            } else {
                out.println("<div class='reserve-badge' style='display: inline-block; margin: 0.5rem 0;'>No Reserve</div>");
            }
        }
        
        out.println("<div class='item-price'>Current Bid: $" + String.format("%.2f", startOrCurrent) + "</div>");
        out.println("<p style='color: var(--text-secondary); font-size: 0.9rem;'><strong>⏰ Closes:</strong> " + auctionDateVal + " at " + auctionTimeVal + "</p>");
        out.println("</div>");
        
        out.println("<div class='item-footer'>");
        out.println("<form method='get' action='shoes.jsp' style='display:inline;'>");
        out.println("<input type='hidden' name='similarId' value='" + shoeIdVal + "'>");
        out.println("<input type='hidden' name='similarSize' value='" + (sizeVal != null ? sizeVal : "") + "'>");
        out.println("<input type='hidden' name='similarGender' value='" + (genderVal != null ? genderVal : "") + "'>");
        out.println("<input type='hidden' name='similarMinPrice' value='" + simMinPrice + "'>");
        out.println("<input type='hidden' name='similarMaxPrice' value='" + simMaxPrice + "'>");
        out.println("<button type='submit' class='btn btn-outline' style='font-size: 0.9rem; padding: 0.5rem 1rem;'>🔍 Show Similars</button>");
        out.println("</form>");
        out.println("</div>");
        out.println("</div>");
    }

    if (!found) {
        out.println("</div>"); // Close items-grid
        out.println("<div class='card'>");
        out.println("<p style='text-align: center; color: var(--text-secondary); font-size: 1.1rem;'>No shoes found matching your criteria.</p>");
        out.println("</div>");
    } else {
        out.println("</div>"); // Close items-grid
    }

    rs.close();
    st.close();
    con.close();

      out.write("\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
