/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-07 00:09:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.Part;
import java.io.*;
import java.sql.*;
import jakarta.servlet.annotation.MultipartConfig;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;

public final class tops_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("jakarta.servlet.http.Part");
    _jspx_imports_classes.add("jakarta.servlet.annotation.MultipartConfig");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.LocalTime");
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Tops - ThriftShop Auction</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/auction-style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Header -->\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <div class=\"header-container\">\n");
      out.write("            <a href=\"mainPage.jsp\" class=\"logo\">🏛️ ThriftShop</a>\n");
      out.write("            <nav>\n");
      out.write("                <ul class=\"nav-menu\">\n");
      out.write("                    <li><a href=\"tops.jsp\">Tops</a></li>\n");
      out.write("                    <li><a href=\"bottoms.jsp\">Bottoms</a></li>\n");
      out.write("                    <li><a href=\"shoes.jsp\">Shoes</a></li>\n");
      out.write("                    <li><a href=\"sellers.jsp\">Sellers</a></li>\n");
      out.write("                    <li><a href=\"notifications.jsp\">Notifications</a></li>\n");
      out.write("                    <li><a href=\"profile.jsp\">Profile</a></li>\n");
      out.write("                    <li><a href=\"../LoginPage/logout.jsp\">Logout</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"user-info\">👤 ");
      out.print(session.getAttribute("username"));
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("\n");

    // load MySQL driver
    Class.forName("com.mysql.cj.jdbc.Driver");
    String jdbcUrl = System.getenv("JDBC_URL");
    if (jdbcUrl == null || jdbcUrl.isEmpty()) {
        String dbHost = System.getenv("DB_HOST");
        String dbPort = System.getenv("DB_PORT");
        String dbName = System.getenv("DB_NAME");
        if (dbHost == null) dbHost = "localhost";
        if (dbPort == null) dbPort = "3306";
        if (dbName == null) dbName = "thriftShop";
        jdbcUrl = "jdbc:mysql://" + dbHost + ":" + dbPort + "/" + dbName;
    }
    String dbUser = System.getenv("DB_USER");
    if (dbUser == null) dbUser = "root";
    String dbPass = System.getenv("DB_PASS");
    if (dbPass == null) dbPass = "12345";
    Connection con = DriverManager.getConnection(jdbcUrl, dbUser, dbPass);
    Statement st = con.createStatement();


    if (session.getAttribute("username") == null) {
        response.sendRedirect("../LoginPage/login.jsp");
        return;
    }

      out.write("\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("    <h1>👔 Tops</h1>\n");
      out.write("    <p>Browse and bid on premium tops</p>\n");
      out.write("    <a href=\"mainPage.jsp\" class=\"btn btn-outline\" style=\"margin-top: 1rem;\">← Back to Main Page</a>\n");
      out.write("</div>\n");


    String similarId = request.getParameter("similarId");
    String similarSize = request.getParameter("similarSize");
    String similarGender = request.getParameter("similarGender");
    String similarMinPrice = request.getParameter("similarMinPrice");
    String similarMaxPrice = request.getParameter("similarMaxPrice");

    boolean showingSimilar = (similarSize != null && !similarSize.isEmpty() &&
            similarGender != null && !similarGender.isEmpty());

    if (showingSimilar) {
        out.println("<p><strong>Showing Similar Tops:</strong> Gender \"" + similarGender + "\" | Size \"" + similarSize + "\" | Price: $" + similarMinPrice + " - $" + similarMaxPrice);
        out.println("&nbsp;&nbsp;<a href='tops.jsp'>Clear Filter</a></p>");
        out.println("<hr/>");
    }

    int counter = 0;

      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function createBid(counter) {\n");
      out.write("        var SetNewBidLabel = document.getElementById('SetNewBidLabel' + counter);\n");
      out.write("        var SetNewBid = document.getElementById('SetNewBid' + counter);\n");
      out.write("        var SetAutomaticBidLabel = document.getElementById('SetAutomaticBidLabel' + counter);\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("        var cancel = document.getElementById('cancel' + counter);\n");
      out.write("        var PlaceBid = document.getElementById('TopPlaceBid' + counter);\n");
      out.write("\n");
      out.write("        SetNewBidLabel.style.display = 'block';\n");
      out.write("        SetNewBid.style.display = 'block';\n");
      out.write("        SetAutomaticBidLabel.style.display = 'block';\n");
      out.write("        SetAutomaticBid.style.display = 'block';\n");
      out.write("        cancel.style.display = 'block';\n");
      out.write("        PlaceBid.style.display = 'block';\n");
      out.write("\n");
      out.write("        SetAutomaticBid.addEventListener(\"change\", function() {\n");
      out.write("            handleAutomaticBidChange(counter);\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function handleAutomaticBidChange(counter) {\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("        var SetAutomaticBidPriceLabel = document.getElementById('SetAutomaticBidPriceLabel' + counter);\n");
      out.write("        var SetAutomaticBidPrice = document.getElementById('SetAutomaticBidPrice' + counter);\n");
      out.write("        var SetAutomaticBidIncrementPriceLabel = document.getElementById('SetAutomaticBidIncrementPriceLabel' + counter);\n");
      out.write("        var SetAutomaticBidIncrementPrice = document.getElementById('SetAutomaticBidIncrementPrice' + counter);\n");
      out.write("\n");
      out.write("        const value = SetAutomaticBid.value;\n");
      out.write("\n");
      out.write("        if (value === 'true') {\n");
      out.write("            SetAutomaticBidPriceLabel.style.display = 'block';\n");
      out.write("            SetAutomaticBidPrice.style.display = 'block';\n");
      out.write("            SetAutomaticBidIncrementPriceLabel.style.display = 'block';\n");
      out.write("            SetAutomaticBidIncrementPrice.style.display = 'block';\n");
      out.write("        } else {\n");
      out.write("            SetAutomaticBidPriceLabel.style.display = 'none';\n");
      out.write("            SetAutomaticBidPrice.style.display = 'none';\n");
      out.write("            SetAutomaticBidIncrementPriceLabel.style.display = 'none';\n");
      out.write("            SetAutomaticBidIncrementPrice.style.display = 'none';\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function removeBid(counter) {\n");
      out.write("        var SetNewBidLabel = document.getElementById('SetNewBidLabel' + counter);\n");
      out.write("        var SetNewBid = document.getElementById('SetNewBid' + counter);\n");
      out.write("        var SetAutomaticBidLabel = document.getElementById('SetAutomaticBidLabel' + counter);\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\n");
      out.write("        var SetAutomaticBidPriceLabel = document.getElementById('SetAutomaticBidPriceLabel' + counter);\n");
      out.write("        var SetAutomaticBidPrice = document.getElementById('SetAutomaticBidPrice' + counter);\n");
      out.write("        var SetAutomaticBidIncrementPriceLabel = document.getElementById('SetAutomaticBidIncrementPriceLabel' + counter);\n");
      out.write("        var SetAutomaticBidIncrementPrice = document.getElementById('SetAutomaticBidIncrementPrice' + counter);\n");
      out.write("        var cancel = document.getElementById('cancel' + counter);\n");
      out.write("        var PlaceBid = document.getElementById('TopPlaceBid' + counter);\n");
      out.write("\n");
      out.write("        SetNewBidLabel.style.display = 'none';\n");
      out.write("        SetNewBid.style.display = 'none';\n");
      out.write("        SetAutomaticBidLabel.style.display = 'none';\n");
      out.write("        SetAutomaticBid.style.display = 'none';\n");
      out.write("        SetAutomaticBidPriceLabel.style.display = 'none';\n");
      out.write("        SetAutomaticBidPrice.style.display = 'none';\n");
      out.write("        SetAutomaticBidIncrementPriceLabel.style.display = 'none';\n");
      out.write("        SetAutomaticBidIncrementPrice.style.display = 'none';\n");
      out.write("        cancel.style.display = 'none';\n");
      out.write("        PlaceBid.style.display = 'none';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function placeBid(counter) {\n");
      out.write("        // submit handled by bidPage.jsp\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");


    String gender = request.getParameter("topGender");
    if (gender != null) {


        String dateStr = request.getParameter("AuctionCloseDateTops");
        String timeStr = request.getParameter("AuctionCloseTimeTops");

        if (dateStr == null || timeStr == null ||
                dateStr.isEmpty() || timeStr.isEmpty()) {

            out.println("<p style='color:red'>Error. Auction close date or time is missing.</p>");
            out.println("<a href='../WebsitePages/mainPage.jsp'>Go back to Main Page</a>");
            st.close();
            con.close();
            return;
        }

        LocalDate closeDate = LocalDate.parse(dateStr);
        LocalTime closeTime = LocalTime.parse(timeStr);
        LocalDateTime closeDateTime = LocalDateTime.of(closeDate, closeTime);
        LocalDateTime now = LocalDateTime.now();

        if (closeDateTime.isBefore(now)) {
            out.println("<p style='color:red'>Auction close date and time cannot be in the past.</p>");
            out.println("<a href='../WebsitePages/mainPage.jsp'>Go back to Main Page</a>");
            st.close();
            con.close();
            return;
        }


        Integer userIdValue = (Integer) session.getAttribute("userIdValue");
        String size = request.getParameter("topSize");
        String color = request.getParameter("topColor");
        Float frontlength = Float.parseFloat(request.getParameter("FrontLength"));
        Float chestlength = Float.parseFloat(request.getParameter("ChestLength"));
        Float sleevelength = Float.parseFloat(request.getParameter("SleeveLength"));
        String description = request.getParameter("Description");
        String condition = request.getParameter("Condition");
        String minimum = request.getParameter("Minimum");
        String startingorcurrentbidprice = request.getParameter("StartingOrCurrentBidPrice");

        String auctionclosedate = dateStr;
        String auctionclosetime = timeStr;

        if (minimum == null || minimum.isEmpty()) {
            minimum = "0.0";
        }

        String insertTopInformation =
                "INSERT INTO tops " +
                        "(auctionSellerIdValue, genderValue, sizeValue, colorValue, " +
                        " frontLengthValue, chestLengthValue, sleeveLengthValue, " +
                        " descriptionValue, conditionValue, minimumBidPriceValue, " +
                        " startingOrCurrentBidPriceValue, auctionCloseDateValue, auctionCloseTimeValue) " +
                        "VALUES ('" + userIdValue + "','" + gender + "','" + size + "','" + color + "'," +
                        "'" + frontlength + "','" + chestlength + "','" + sleevelength + "'," +
                        "'" + description + "','" + condition + "','" + minimum + "','" +
                        startingorcurrentbidprice + "','" + auctionclosedate + "','" + auctionclosetime + "')";

        st.executeUpdate(insertTopInformation);
    }


    StringBuilder topsQuery = new StringBuilder(
            "SELECT t.*, u.usernameValue AS sellerUsername " +
                    "FROM tops t " +
                    "JOIN users u ON t.auctionSellerIdValue = u.userIdValue " +
                    "WHERE 1=1");

    if (showingSimilar) {

        if (similarGender != null && !similarGender.isEmpty()) {
            String safeGender = similarGender.replace("'", "''");
            topsQuery.append(" AND t.genderValue = '").append(safeGender).append("'");
        }

        if (similarSize != null && !similarSize.isEmpty()) {
            String safeSize = similarSize.replace("'", "''");
            topsQuery.append(" AND t.sizeValue = '").append(safeSize).append("'");
        }

        if (similarMinPrice != null && !similarMinPrice.isEmpty()) {
            topsQuery.append(" AND t.minimumBidPriceValue >= ").append(similarMinPrice);
        }
        if (similarMaxPrice != null && !similarMaxPrice.isEmpty()) {
            topsQuery.append(" AND t.minimumBidPriceValue <= ").append(similarMaxPrice);
        }

        if (similarId != null && !similarId.isEmpty()) {
            topsQuery.append(" AND t.topIdValue != ").append(similarId);
        }
    }

    topsQuery.append(" ORDER BY t.topIdValue DESC");

    ResultSet rs = st.executeQuery(topsQuery.toString());
    boolean found = false;
    
    out.println("<div class='items-grid'>");
    
    while (rs.next()) {
        found = true;
        String sellerUsername  = rs.getString("sellerUsername");
        String topIdValueDisplay = rs.getString("topIdValue");
        String genderValueDisplay = rs.getString("genderValue");
        String sizeValueDisplay = rs.getString("sizeValue");
        String colorValueDisplay = rs.getString("colorValue");
        String frontLengthValueDisplay = rs.getString("frontLengthValue");
        String chestLengthValueDisplay = rs.getString("chestLengthValue");
        String sleeveLengthValueDisplay = rs.getString("sleeveLengthValue");
        String descriptionValueDisplay = rs.getString("descriptionValue");
        String conditionValueDisplay = rs.getString("conditionValue");
        float minimumBidPriceValueDisplay = rs.getFloat("minimumBidPriceValue");
        float startingOrCurrentBidPriceValueDisplay = rs.getFloat("startingOrCurrentBidPriceValue");
        String auctionCloseDateValueDisplay = rs.getString("auctionCloseDateValue");
        String auctionCloseTimeValueDisplay = rs.getString("auctionCloseTimeValue");


        double simMinPrice = Math.round(minimumBidPriceValueDisplay * 0.9 * 100.0) / 100.0;
        double simMaxPrice = Math.round(minimumBidPriceValueDisplay * 1.1 * 100.0) / 100.0;


        Integer currentUserId = (Integer) session.getAttribute("userIdValue");
        String sellerIdStr = rs.getString("auctionSellerIdValue");
        boolean isSeller = (currentUserId != null && sellerIdStr != null && 
                           currentUserId.toString().equals(sellerIdStr));

        out.println("<div class='item-card'>");
        out.println("<div class='item-image'>👔</div>");
        out.println("<div class='item-body'>");
        out.println("<div class='item-title'>" + (descriptionValueDisplay != null && !descriptionValueDisplay.isEmpty() ? descriptionValueDisplay : "Top #" + topIdValueDisplay) + "</div>");
        out.println("<div class='item-meta'>");
        out.println("<span>👤 Seller: " + sellerUsername + "</span> | ");
        out.println("<span>" + genderValueDisplay + "</span> | ");
        out.println("<span>Size: " + sizeValueDisplay + "</span> | ");
        out.println("<span>Color: " + colorValueDisplay + "</span>");
        out.println("</div>");
        
        out.println("<div style='margin: 1rem 0; padding: 1rem; background: var(--bg-light); border-radius: 8px;'>");
        out.println("<p style='margin: 0.5rem 0;'><strong>📏 Measurements:</strong></p>");
        out.println("<p style='margin: 0.25rem 0; color: var(--text-secondary);'>Front: " + frontLengthValueDisplay + "cm | Chest: " + chestLengthValueDisplay + "cm | Sleeve: " + sleeveLengthValueDisplay + "cm</p>");
        out.println("</div>");
        
        out.println("<p style='margin: 0.5rem 0;'><strong>📝 Description:</strong> " + descriptionValueDisplay + "</p>");
        out.println("<p style='margin: 0.5rem 0;'><strong>✨ Condition:</strong> " + conditionValueDisplay + "</p>");
        
        if (isSeller) {
            if (minimumBidPriceValueDisplay != 0.0f) {
                out.println("<div class='reserve-badge' style='display: inline-block; margin: 0.5rem 0;'>🔒 Reserve: $" + minimumBidPriceValueDisplay + " (Hidden)</div>");
            } else {
                out.println("<div class='reserve-badge' style='display: inline-block; margin: 0.5rem 0;'>No Reserve</div>");
            }
        }
        
        out.println("<div class='item-price'>Current Bid: $" + String.format("%.2f", startingOrCurrentBidPriceValueDisplay) + "</div>");
        out.println("<p style='color: var(--text-secondary); font-size: 0.9rem;'><strong>⏰ Closes:</strong> " + auctionCloseDateValueDisplay + " at " + auctionCloseTimeValueDisplay + "</p>");
        out.println("</div>");
        
        out.println("<div class='item-footer'>");
        out.println("<form method='get' action='tops.jsp' style='display:inline;'>");
        out.println("<input type='hidden' name='similarId' value='" + topIdValueDisplay + "'>");
        out.println("<input type='hidden' name='similarSize' value='" + (sizeValueDisplay != null ? sizeValueDisplay : "") + "'>");
        out.println("<input type='hidden' name='similarGender' value='" + (genderValueDisplay != null ? genderValueDisplay : "") + "'>");
        out.println("<input type='hidden' name='similarMinPrice' value='" + simMinPrice + "'>");
        out.println("<input type='hidden' name='similarMaxPrice' value='" + simMaxPrice + "'>");
        out.println("<button type='submit' class='btn btn-outline' style='font-size: 0.9rem; padding: 0.5rem 1rem;'>🔍 Show Similars</button>");
        out.println("</form>");
        
        out.println("<button type='button' onclick='createBid(" + counter + ")' class='btn btn-primary' id='TopCreateBid" + counter + "' style='font-size: 0.9rem; padding: 0.5rem 1rem;'>💰 Place Bid</button>");

        out.println("<form method='post' action='bidPage.jsp' style='margin-top: 1rem; padding-top: 1rem; border-top: 1px solid var(--border-color);'>");
        out.println("<input type='hidden' name='topIdValue' value='" + topIdValueDisplay + "'>");
        out.println("<div class='form-group' id='SetNewBidLabel" + counter + "' style='display: none;'>");
        out.println("<label for='setNewBid" + counter + "'>Bid Amount (USD)</label>");
        out.println("<input type='number' name='setNewBid' id='SetNewBid" + counter + "' class='form-control' step='0.01' min='" + startingOrCurrentBidPriceValueDisplay + "' required>");
        out.println("</div>");
        out.println("<div class='form-group' id='SetAutomaticBidLabel" + counter + "' style='display: none;'>");
        out.println("<label for='setAutomaticBid" + counter + "'>Enable Automatic Bidding?</label>");
        out.println("<select name='setAutomaticBid' id='SetAutomaticBid" + counter + "' class='form-control' required>");
        out.println("<option value='selectAnItem' disabled selected>Select...</option>");
        out.println("<option value='true'>Yes</option>");
        out.println("<option value='false'>No</option>");
        out.println("</select>");
        out.println("</div>");
        out.println("<div class='form-group' id='SetAutomaticBidPriceLabel" + counter + "' style='display: none;'>");
        out.println("<label for='maxBidPrice" + counter + "'>Maximum Bid (USD)</label>");
        out.println("<input type='number' name='maxBidPrice' id='SetAutomaticBidPrice" + counter + "' class='form-control' step='0.01' min='0'>");
        out.println("</div>");
        out.println("<div class='form-group' id='SetAutomaticBidIncrementPriceLabel" + counter + "' style='display: none;'>");
        out.println("<label for='SetAutomaticBidIncrementPrice" + counter + "'>Bid Increment (USD)</label>");
        out.println("<input type='number' name='SetAutomaticBidIncrementPrice' id='SetAutomaticBidIncrementPrice" + counter + "' class='form-control' step='0.01' min='0'>");
        out.println("</div>");
        out.println("<div style='display: flex; gap: 0.5rem; margin-top: 1rem;'>");
        out.println("<button type='button' onclick='removeBid(" + counter + ")' class='btn btn-outline' id='cancel" + counter + "' style='display: none;'>Cancel</button>");
        out.println("<button type='submit' class='btn btn-primary' id='TopPlaceBid" + counter + "' style='display: none;'>Submit Bid</button>");
        out.println("</div>");
        out.println("</form>");
        out.println("</div>");
        out.println("</div>");

        counter++;
    }

    if (!found) {
        out.println("</div>");
        out.println("<div class='card'>");
        out.println("<p style='text-align: center; color: var(--text-secondary); font-size: 1.1rem;'>No tops found matching your criteria.</p>");
        out.println("</div>");
    } else {
        out.println("</div>");
    }

    String alertMessage = (String) session.getAttribute("alertMessage");
    if (alertMessage != null) {
        session.removeAttribute("alertMessage");
        if (alertMessage.equals("success")) {

      out.write("\n");
      out.write("<script>\n");
      out.write("    alert(\"Your bid has been successfully placed!\");\n");
      out.write("</script>\n");

} else if (alertMessage.equals("fail")) {

      out.write("\n");
      out.write("<script>\n");
      out.write("    alert(\"Your bid must be higher than the original price!\");\n");
      out.write("</script>\n");

        }
    }

    rs.close();
    st.close();
    con.close();

      out.write("\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
