/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-12-06 20:09:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebsitePages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.Part;
import java.io.*;
import java.sql.*;
import jakarta.servlet.annotation.MultipartConfig;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;

public final class tops_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("jakarta.servlet.http.Part");
    _jspx_imports_classes.add("jakarta.servlet.annotation.MultipartConfig");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.LocalTime");
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // load MySQL driver
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/thriftShop","root", "12345");
    Statement st = con.createStatement();

    // check login
    if (session.getAttribute("username") == null) {
        response.sendRedirect("../LoginPage/login.jsp");
        return;
    }

    out.println("<h3>User: " + session.getAttribute("username") + "</h3>");
    out.println("<a href='../WebsitePages/mainPage.jsp'>Main Page</a>");
    out.println("<br/>This is the Tops page<br/><br/>");

    int counter = 0;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function createBid(counter) {\r\n");
      out.write("        var SetNewBidLabel = document.getElementById('SetNewBidLabel' + counter);\r\n");
      out.write("        var SetNewBid = document.getElementById('SetNewBid' + counter);\r\n");
      out.write("        var SetAutomaticBidLabel = document.getElementById('SetAutomaticBidLabel' + counter);\r\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\r\n");
      out.write("        var cancel = document.getElementById('cancel' + counter);\r\n");
      out.write("        var PlaceBid = document.getElementById('TopPlaceBid' + counter);\r\n");
      out.write("\r\n");
      out.write("        SetNewBidLabel.style.display = 'block';\r\n");
      out.write("        SetNewBid.style.display = 'block';\r\n");
      out.write("        SetAutomaticBidLabel.style.display = 'block';\r\n");
      out.write("        SetAutomaticBid.style.display = 'block';\r\n");
      out.write("        cancel.style.display = 'block';\r\n");
      out.write("        PlaceBid.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("        SetAutomaticBid.addEventListener(\"change\", function() {\r\n");
      out.write("            handleAutomaticBidChange(counter);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function handleAutomaticBidChange(counter) {\r\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\r\n");
      out.write("        var SetAutomaticBidPriceLabel = document.getElementById('SetAutomaticBidPriceLabel' + counter);\r\n");
      out.write("        var SetAutomaticBidPrice = document.getElementById('SetAutomaticBidPrice' + counter);\r\n");
      out.write("        var SetAutomaticBidIncrementPriceLabel = document.getElementById('SetAutomaticBidIncrementPriceLabel' + counter);\r\n");
      out.write("        var SetAutomaticBidIncrementPrice = document.getElementById('SetAutomaticBidIncrementPrice' + counter);\r\n");
      out.write("\r\n");
      out.write("        const value = SetAutomaticBid.value;\r\n");
      out.write("\r\n");
      out.write("        if (value === 'true') {\r\n");
      out.write("            SetAutomaticBidPriceLabel.style.display = 'block';\r\n");
      out.write("            SetAutomaticBidPrice.style.display = 'block';\r\n");
      out.write("            SetAutomaticBidIncrementPriceLabel.style.display = 'block';\r\n");
      out.write("            SetAutomaticBidIncrementPrice.style.display = 'block';\r\n");
      out.write("        } else {\r\n");
      out.write("            SetAutomaticBidPriceLabel.style.display = 'none';\r\n");
      out.write("            SetAutomaticBidPrice.style.display = 'none';\r\n");
      out.write("            SetAutomaticBidIncrementPriceLabel.style.display = 'none';\r\n");
      out.write("            SetAutomaticBidIncrementPrice.style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function removeBid(counter) {\r\n");
      out.write("        var SetNewBidLabel = document.getElementById('SetNewBidLabel' + counter);\r\n");
      out.write("        var SetNewBid = document.getElementById('SetNewBid' + counter);\r\n");
      out.write("        var SetAutomaticBidLabel = document.getElementById('SetAutomaticBidLabel' + counter);\r\n");
      out.write("        var SetAutomaticBid = document.getElementById('SetAutomaticBid' + counter);\r\n");
      out.write("        var SetAutomaticBidPriceLabel = document.getElementById('SetAutomaticBidPriceLabel' + counter);\r\n");
      out.write("        var SetAutomaticBidPrice = document.getElementById('SetAutomaticBidPrice' + counter);\r\n");
      out.write("        var SetAutomaticBidIncrementPriceLabel = document.getElementById('SetAutomaticBidIncrementPriceLabel' + counter);\r\n");
      out.write("        var SetAutomaticBidIncrementPrice = document.getElementById('SetAutomaticBidIncrementPrice' + counter);\r\n");
      out.write("        var cancel = document.getElementById('cancel' + counter);\r\n");
      out.write("        var PlaceBid = document.getElementById('TopPlaceBid' + counter);\r\n");
      out.write("\r\n");
      out.write("        SetNewBidLabel.style.display = 'none';\r\n");
      out.write("        SetNewBid.style.display = 'none';\r\n");
      out.write("        SetAutomaticBidLabel.style.display = 'none';\r\n");
      out.write("        SetAutomaticBid.style.display = 'none';\r\n");
      out.write("        SetAutomaticBidPriceLabel.style.display = 'none';\r\n");
      out.write("        SetAutomaticBidPrice.style.display = 'none';\r\n");
      out.write("        SetAutomaticBidIncrementPriceLabel.style.display = 'none';\r\n");
      out.write("        SetAutomaticBidIncrementPrice.style.display = 'none';\r\n");
      out.write("        cancel.style.display = 'none';\r\n");
      out.write("        PlaceBid.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function placeBid(counter) {\r\n");
      out.write("        // submit handled by bidPage.jsp\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");

    // handle new top auction submit
    String gender = request.getParameter("topGender");
    if (gender != null) {

        // read date and time
        String dateStr = request.getParameter("AuctionCloseDateTops");
        String timeStr = request.getParameter("AuctionCloseTimeTops");

        if (dateStr == null || timeStr == null ||
                dateStr.isEmpty() || timeStr.isEmpty()) {

            out.println("<p style='color:red'>Error. Auction close date or time is missing.</p>");
            out.println("<a href='../WebsitePages/mainPage.jsp'>Go back to Main Page</a>");
            st.close();
            con.close();
            return;
        }

        LocalDate closeDate = LocalDate.parse(dateStr);
        LocalTime closeTime = LocalTime.parse(timeStr);
        LocalDateTime closeDateTime = LocalDateTime.of(closeDate, closeTime);
        LocalDateTime now = LocalDateTime.now();

        if (closeDateTime.isBefore(now)) {
            out.println("<p style='color:red'>Auction close date and time cannot be in the past.</p>");
            out.println("<a href='../WebsitePages/mainPage.jsp'>Go back to Main Page</a>");
            st.close();
            con.close();
            return;
        }

        // date and time are ok, read rest of fields
        Integer userIdValue = (Integer) session.getAttribute("userIdValue");
        String size = request.getParameter("topSize");
        String color = request.getParameter("topColor");
        Float frontlength = Float.parseFloat(request.getParameter("FrontLength"));
        Float chestlength = Float.parseFloat(request.getParameter("ChestLength"));
        Float sleevelength = Float.parseFloat(request.getParameter("SleeveLength"));
        String description = request.getParameter("Description");
        String condition = request.getParameter("Condition");
        String minimum = request.getParameter("Minimum");
        String startingorcurrentbidprice = request.getParameter("StartingOrCurrentBidPrice");

        String auctionclosedate = dateStr;
        String auctionclosetime = timeStr;

        if (minimum == null || minimum.isEmpty()) {
            minimum = "0.0";
        }

        String insertTopInformation =
                "INSERT INTO tops " +
                        "(auctionSellerIdValue, genderValue, sizeValue, colorValue, " +
                        " frontLengthValue, chestLengthValue, sleeveLengthValue, " +
                        " descriptionValue, conditionValue, minimumBidPriceValue, " +
                        " startingOrCurrentBidPriceValue, auctionCloseDateValue, auctionCloseTimeValue) " +
                        "VALUES ('" + userIdValue + "','" + gender + "','" + size + "','" + color + "'," +
                        "'" + frontlength + "','" + chestlength + "','" + sleevelength + "'," +
                        "'" + description + "','" + condition + "','" + minimum + "','" +
                        startingorcurrentbidprice + "','" + auctionclosedate + "','" + auctionclosetime + "')";

        st.executeUpdate(insertTopInformation);
    }

    // query tops joined with users to get seller username
    String topsQuery =
            "SELECT t.*, u.usernameValue AS sellerUsername " +
                    "FROM tops t " +
                    "JOIN users u ON t.auctionSellerIdValue = u.userIdValue " +
                    "ORDER BY t.topIdValue DESC";

    ResultSet rs = st.executeQuery(topsQuery);
    while (rs.next()) {
        String sellerUsername  = rs.getString("sellerUsername");
        String topIdValueDisplay = rs.getString("topIdValue");
        String genderValueDisplay = rs.getString("genderValue");
        String sizeValueDisplay = rs.getString("sizeValue");
        String colorValueDisplay = rs.getString("colorValue");
        String frontLengthValueDisplay = rs.getString("frontLengthValue");
        String chestLengthValueDisplay = rs.getString("chestLengthValue");
        String sleeveLengthValueDisplay = rs.getString("sleeveLengthValue");
        String descriptionValueDisplay = rs.getString("descriptionValue");
        String conditionValueDisplay = rs.getString("conditionValue");
        float minimumBidPriceValueDisplay = rs.getFloat("minimumBidPriceValue");
        float startingOrCurrentBidPriceValueDisplay = rs.getFloat("startingOrCurrentBidPriceValue");
        String auctionCloseDateValueDisplay = rs.getString("auctionCloseDateValue");
        String auctionCloseTimeValueDisplay = rs.getString("auctionCloseTimeValue");

        out.println("<div>");
        out.println("<p><strong>Seller:</strong> " + sellerUsername + "</p>");
        out.println("<p><strong>Gender:</strong> " + genderValueDisplay + "</p>");
        out.println("<p><strong>Size:</strong> " + sizeValueDisplay + "</p>");
        out.println("<p><strong>Color:</strong> " + colorValueDisplay + "</p>");
        out.println("<p><strong>Front Length:</strong> " + frontLengthValueDisplay + "</p>");
        out.println("<p><strong>Chest Length:</strong> " + chestLengthValueDisplay + "</p>");
        out.println("<p><strong>Sleeve Length:</strong> " + sleeveLengthValueDisplay + "</p>");
        out.println("<p><strong>Description:</strong> " + descriptionValueDisplay + "</p>");
        out.println("<p><strong>Condition:</strong> " + conditionValueDisplay + "</p>");

        if (minimumBidPriceValueDisplay != 0.0f) {
            out.println("<p><strong>Minimum Bid Price: </strong>" + minimumBidPriceValueDisplay + "</p>");
        } else {
            out.println("<p><strong>Minimum Bid Price:</strong> None</p>");
        }

        out.println("<p><strong>Starting or Current Bid Price: </strong>" + startingOrCurrentBidPriceValueDisplay + "</p>");
        out.println("<p><strong>Auction Close Date: </strong>" + auctionCloseDateValueDisplay + "</p>");
        out.println("<p><strong>Auction Close Time: </strong>" + auctionCloseTimeValueDisplay + "</p>");

        out.println("<input type='button' value='Create Bid' onclick='createBid(" + counter + ")' id='TopCreateBid" + counter + "' style='margin-bottom: 100px;'>");

        out.println("<form method='post' action='bidPage.jsp'>");
        out.println("<input type='hidden' name='topIdValue' value='" + topIdValueDisplay + "'>");
        out.println("<label for='setNewBid' id='SetNewBidLabel" + counter + "' style='display: none;'>Set Bid (USD): </label>");
        out.println("<input type='number' name='setNewBid' id='SetNewBid" + counter + "' style='display: none;' required>");
        out.println("<label for='setAutomaticBid' id='SetAutomaticBidLabel" + counter + "' style='display: none;'>Set Automatic Bid: </label>");
        out.println("<select name='setAutomaticBid' id='SetAutomaticBid" + counter + "' style='display: none;' required>");
        out.println("<option value='selectAnItem' disabled selected>Select Item...</option>");
        out.println("<option value='true' id='true'>Yes</option>");
        out.println("<option value='false' id='false'>No</option>");
        out.println("</select>");
        out.println("<label for='maxBidPrice' id='SetAutomaticBidPriceLabel" + counter + "' style='display: none;'>Set Max Bid Price (USD): </label>");
        out.println("<input type='number' name='maxBidPrice' id='SetAutomaticBidPrice" + counter + "' style='display: none;'>");
        out.println("<label for='SetAutomaticBidIncrementPrice' id='SetAutomaticBidIncrementPriceLabel" + counter + "' style='display: none;'>Set Bid Increment Price (USD): </label>");
        out.println("<input type='number' name='SetAutomaticBidIncrementPrice' id='SetAutomaticBidIncrementPrice" + counter + "' style='display: none;'>");
        out.println("<input type='button' value='Cancel Bid' onclick='removeBid(" + counter + ")' id='cancel" + counter + "' style='display: none;'>");
        out.println("<input type='submit' value='Place Bid' onclick='placeBid(" + counter +")' id='TopPlaceBid" + counter + "' style='display: none;'>");
        out.println("</form>");
        out.println("</div>");

        counter++;
    }

    // show alerts from bidPage.jsp
    String alertMessage = (String) session.getAttribute("alertMessage");
    if (alertMessage != null) {
        session.removeAttribute("alertMessage");
        if (alertMessage.equals("success")) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    alert(\"Your bid has been successfully placed!\");\r\n");
      out.write("</script>\r\n");

} else if (alertMessage.equals("fail")) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    alert(\"Your bid must be higher than the original price!\");\r\n");
      out.write("</script>\r\n");

        }
    }

    rs.close();
    st.close();
    con.close();

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
